package com.micatechnologies.minecraft.csm.tools.tool_framework;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/**
 * The multi-tree source layout of the mod, for the development tools.
 *
 * <p>CSM is built from several source trees: Core at {@code src/main} plus one per optional
 * module under {@code modules/&lt;name&gt;/src/main} (see {@code modules.gradle}). Every tree
 * puts its resources under the same {@code assets/csm} domain, because Forge merges a resource
 * domain across every jar that declares it. That has two consequences for any tool that touches
 * the tree:
 *
 * <ul>
 *   <li>Anything that <em>reads</em> an asset must look in the union of the trees. A tool that
 *       only opens {@code src/main/resources/assets/csm} now sees Core alone, which is a handful
 *       of files, and reports a clean bill of health for a mod it never looked at.</li>
 *   <li>Anything that <em>writes</em> an asset must write it into the tree that ships it. Writing
 *       to Core instead would put a second copy of the file in a second jar, and which one the
 *       game loads is then down to classpath order.</li>
 * </ul>
 *
 * <p>Ownership of a block's assets follows the block: the tree holding its blockstate owns it,
 * and for a block whose blockstate does not exist yet, the tree holding the creative tab that
 * registers it, falling back to the tree holding its Java class (which is how hidden blocks and
 * blocks in no tab at all resolve).
 *
 * <p>Instances are cheap to create but cache their source scan, so a tool should create one and
 * pass it around rather than making a new one per lookup.
 *
 * @version 1.0
 * @since 2025.9.3
 */
public class CsmLayout
{
    /**
     * The module name used for Core, whose tree is the repository's own {@code src/main}.
     *
     * @since 1.0
     */
    public static final String CORE = "core";

    /**
     * The Java package every source tree shares below its {@code src/main/java} root.
     *
     * @since 1.0
     */
    public static final String JAVA_PACKAGE = "com/micatechnologies/minecraft/csm";

    /**
     * The asset domain every tree writes into. Modules do not get a domain of their own.
     *
     * @since 1.0
     */
    public static final String ASSETS_CSM = "assets/csm";

    /**
     * Variants generated by {@code AbstractBlockSetBasic} for each set block.
     *
     * @since 1.0
     */
    private static final String[] BLOCK_SET_SUFFIXES = {"_fence", "_slab", "_stairs"};

    private static final Pattern REGISTRY_NAME_RE = Pattern.compile(
            "public\\s+String\\s+getBlockRegistryName\\(\\)\\s*\\{\\s*return\\s*\"([^\"]+)\"\\s*;");
    private static final Pattern ITEM_REGISTRY_NAME_RE = Pattern.compile(
            "public\\s+String\\s+getItemRegistryName\\(\\)\\s*\\{\\s*return\\s*\"([^\"]+)\"\\s*;");
    private static final Pattern TAB_CLASS_RE
            = Pattern.compile("initTab(?:Block|Item)\\(\\s*([\\w.]+)\\.class");
    private static final Pattern TAB_CTOR_RE
            = Pattern.compile("initTab(?:Block|Item)\\(\\s*new\\s+([\\w.]+)\\s*\\(\\s*(?:\"([^\"]+)\")?");
    private static final Pattern TAB_CONST_RE
            = Pattern.compile("initTab(?:Block|Item)\\(\\s*(\\w+)\\.(\\w+)\\s*\\)");
    private static final Pattern TAB_CLASS_IF_LOADED_RE
            = Pattern.compile("initTab(?:Block|Item)IfLoaded\\(\\s*\"[^\"]*\"\\s*,\\s*\"([\\w.]+)\"");
    private static final Pattern HOLDER_CONST_RE = Pattern.compile(
            "public\\s+static\\s+final\\s+\\w+\\s+(\\w+)\\s*=\\s*new\\s+[\\w.]+\\(\\s*\"([^\"]+)\"");
    private static final Pattern SOUND_CONST_RE
            = Pattern.compile("([A-Z][A-Z0-9_]*)\\s*\\(\\s*\"([^\"]+)\"\\s*\\)");

    /**
     * The repository root, i.e. the folder holding {@code src} and {@code modules}.
     *
     * @since 1.0
     */
    private final File repoRoot;

    /**
     * Module name to the folder holding that module's {@code src/main}, Core first. A
     * {@link LinkedHashMap} because every list this class returns is in tree order and Core
     * must come first: it is the tree a shared asset lives in.
     *
     * @since 1.0
     */
    private final Map< String, File > trees = new LinkedHashMap<>();

    /**
     * Simple class name to what the source scan found out about it. Populated on first use.
     *
     * @since 1.0
     */
    private Map< String, SourceClass > classes = null;

    /**
     * Registry name to the module that owns it. Populated on first use.
     *
     * @since 1.0
     */
    private Map< String, String > ownerByRegistryName = null;

    /**
     * Sound event name to the module whose {@code sounds.json} declares it. Populated on first
     * use.
     *
     * @since 1.0
     */
    private Map< String, String > ownerBySoundName = null;

    /**
     * What the source scan records about one Java class.
     *
     * @since 1.0
     */
    public static class SourceClass
    {
        /** The module whose tree declares the class. */
        public final String module;
        /** The class's {@code .java} file. */
        public final File file;
        /** The package below {@code ...minecraft.csm}, or "" at the root of it. */
        public final String packageName;
        /** The name returned by {@code getBlockRegistryName()}, or null. */
        public final String blockRegistryName;
        /** The name returned by {@code getItemRegistryName()}, or null. */
        public final String itemRegistryName;
        /** The direct superclass simple name, or null. */
        public final String superClass;
        /** Whether the class extends {@code AbstractBlockSetBasic}. */
        public final boolean blockSet;
        /** Constant name to registry name for a holder class of pre-built block instances. */
        public final Map< String, String > constants;

        SourceClass( String module, File file, String packageName, String blockRegistryName,
                     String itemRegistryName, String superClass, boolean blockSet,
                     Map< String, String > constants )
        {
            this.module = module;
            this.file = file;
            this.packageName = packageName;
            this.blockRegistryName = blockRegistryName;
            this.itemRegistryName = itemRegistryName;
            this.superClass = superClass;
            this.blockSet = blockSet;
            this.constants = constants;
        }
    }

    /**
     * Creates a layout for the specified repository root.
     *
     * @param repoRoot the folder holding {@code src} and {@code modules}
     *
     * @since 1.0
     */
    public CsmLayout( File repoRoot )
    {
        this.repoRoot = repoRoot;
        trees.put( CORE, repoRoot );
        File modulesDir = new File( repoRoot, "modules" );
        File[] moduleDirs = modulesDir.listFiles();
        if ( moduleDirs != null ) {
            Arrays.sort( moduleDirs );
            for ( File moduleDir : moduleDirs ) {
                if ( new File( moduleDir, "src/main" ).isDirectory() ) {
                    trees.put( moduleDir.getName(), moduleDir );
                }
            }
        }
    }

    /**
     * Creates a layout for the specified repository root.
     *
     * @param repoRoot the folder holding {@code src} and {@code modules}
     *
     * @return the layout
     *
     * @since 1.0
     */
    public static CsmLayout of( File repoRoot )
    {
        return new CsmLayout( repoRoot );
    }

    /**
     * Returns the repository root this layout was created for.
     *
     * @return the repository root
     *
     * @since 1.0
     */
    public File repoRoot()
    {
        return repoRoot;
    }

    /**
     * Returns every module name, {@code "core"} first then the optional modules in directory
     * order.
     *
     * @return the module names
     *
     * @since 1.0
     */
    public List< String > modules()
    {
        return new ArrayList<>( trees.keySet() );
    }

    /**
     * Returns the folder holding the specified module's {@code src/main}.
     *
     * @param module the module name, or {@code "core"}
     *
     * @return the module's folder, or null if there is no such module
     *
     * @since 1.0
     */
    public File treeRoot( String module )
    {
        return trees.get( module );
    }

    /**
     * Returns every tree's {@code src/main/resources} folder that exists, Core first.
     *
     * @return the resource roots
     *
     * @since 1.0
     */
    public List< File > resourceRoots()
    {
        List< File > roots = new ArrayList<>();
        for ( File tree : trees.values() ) {
            File root = new File( tree, "src/main/resources" );
            if ( root.isDirectory() ) {
                roots.add( root );
            }
        }
        return roots;
    }

    /**
     * Returns every tree's {@code src/main/java} folder that exists, Core first.
     *
     * @return the Java source roots
     *
     * @since 1.0
     */
    public List< File > javaRoots()
    {
        List< File > roots = new ArrayList<>();
        for ( File tree : trees.values() ) {
            File root = new File( tree, "src/main/java" );
            if ( root.isDirectory() ) {
                roots.add( root );
            }
        }
        return roots;
    }

    /**
     * Returns every tree's {@code src/main/java/com/micatechnologies/minecraft/csm} folder that
     * exists, Core first. This is the folder the tools mean when they say "the source folder".
     *
     * @return the CSM package roots
     *
     * @since 1.0
     */
    public List< File > javaPackageRoots()
    {
        List< File > roots = new ArrayList<>();
        for ( File root : javaRoots() ) {
            File pkg = new File( root, JAVA_PACKAGE );
            if ( pkg.isDirectory() ) {
                roots.add( pkg );
            }
        }
        return roots;
    }

    /**
     * Returns every tree's {@code src/main/resources/assets/csm} folder that exists, Core first.
     *
     * @return the asset roots
     *
     * @since 1.0
     */
    public List< File > assetRoots()
    {
        List< File > roots = new ArrayList<>();
        for ( File root : resourceRoots() ) {
            File assets = new File( root, ASSETS_CSM );
            if ( assets.isDirectory() ) {
                roots.add( assets );
            }
        }
        return roots;
    }

    /**
     * Returns every existing folder at the specified path below {@code assets/csm}, Core first.
     * Pass {@code "blockstates"} to get every tree's blockstate folder, and so on.
     *
     * @param relativePath the path below {@code assets/csm}, or "" for the asset roots themselves
     *
     * @return the folders that exist
     *
     * @since 1.0
     */
    public List< File > assetDirs( String relativePath )
    {
        List< File > dirs = new ArrayList<>();
        for ( File assets : assetRoots() ) {
            File dir = relativePath.isEmpty() ? assets : new File( assets, relativePath );
            if ( dir.isDirectory() ) {
                dirs.add( dir );
            }
        }
        return dirs;
    }

    /**
     * Returns every existing file at the specified path below {@code assets/csm}, Core first.
     * Several trees legitimately carry a file of the same name: each ships its own
     * {@code sounds.json} and its own {@code lang/en_us.lang}, and the game merges them.
     *
     * @param relativePath the path below {@code assets/csm}
     *
     * @return the files that exist
     *
     * @since 1.0
     */
    public List< File > assetFiles( String relativePath )
    {
        List< File > files = new ArrayList<>();
        for ( File assets : assetRoots() ) {
            File file = new File( assets, relativePath );
            if ( file.isFile() ) {
                files.add( file );
            }
        }
        return files;
    }

    /**
     * Returns the first tree that has the specified asset folder, Core first.
     *
     * @param relativePath the path below {@code assets/csm}
     *
     * @return the folder, or where it would be in Core if no tree has it
     *
     * @since 1.0
     */
    public File assetDirForRead( String relativePath )
    {
        List< File > dirs = assetDirs( relativePath );
        return dirs.isEmpty()
                ? new File( new File( repoRoot, "src/main/resources/" + ASSETS_CSM ), relativePath )
                : dirs.get( 0 );
    }

    /**
     * Returns where a file generated from the contents of an asset folder should be written: in
     * that folder, in the tree that holds it.
     *
     * <p>This is what an atlas generator wants. An atlas belongs beside the tiles it was built
     * from, and those tiles are all in one module's tree; writing the atlas to Core instead would
     * put a second copy of the same resource path in a second jar.
     *
     * @param relativeFolder the folder below {@code assets/csm}
     * @param fileName       the file to write inside it
     *
     * @return the file to write
     *
     * @since 1.0
     */
    public File assetInFolderForWrite( String relativeFolder, String fileName )
    {
        return new File( assetDirForRead( relativeFolder ), fileName );
    }

    /**
     * Returns the first tree that has the specified asset, Core first.
     *
     * @param relativePath the path below {@code assets/csm}, e.g. {@code models/block/foo.json}
     *
     * @return the file, or null if no tree has it
     *
     * @since 1.0
     */
    public File resolveAssetForRead( String relativePath )
    {
        for ( File assets : assetRoots() ) {
            File file = new File( assets, relativePath );
            if ( file.exists() ) {
                return file;
            }
        }
        return null;
    }

    /**
     * Returns the first tree that has the specified resource, Core first. Same as
     * {@link #resolveAssetForRead(String)} but relative to {@code src/main/resources}, for the
     * few things that live outside the {@code csm} domain ({@code pack.mcmeta},
     * {@code marytts/}).
     *
     * @param relativePath the path below {@code src/main/resources}
     *
     * @return the file, or null if no tree has it
     *
     * @since 1.0
     */
    public File resolveResourceForRead( String relativePath )
    {
        for ( File root : resourceRoots() ) {
            File file = new File( root, relativePath );
            if ( file.exists() ) {
                return file;
            }
        }
        return null;
    }

    /**
     * Returns where the specified asset should be written.
     *
     * <p>If any tree already has the file, that copy is returned, whatever the nominated owner:
     * a tool must never leave two jars shipping the same resource path. Otherwise the owner's
     * tree is used, and the parent folders are not created (the caller does that when it writes).
     *
     * @param owner        the module that owns the asset, from {@link #ownerOf(String)}
     * @param relativePath the path below {@code assets/csm}
     *
     * @return the file to write
     *
     * @since 1.0
     */
    public File assetForWrite( String owner, String relativePath )
    {
        File existing = resolveAssetForRead( relativePath );
        if ( existing != null ) {
            return existing;
        }
        File tree = trees.getOrDefault( owner, repoRoot );
        return new File( new File( tree, "src/main/resources/" + ASSETS_CSM ), relativePath );
    }

    /**
     * Returns the first tree that has the specified Java source path, Core first.
     *
     * @param relativePath the path below {@code src/main/java/com/micatechnologies/minecraft/csm},
     *                     e.g. {@code codeutils/AbstractBlockSlab.java} or
     *                     {@code trafficsignals/logic}
     *
     * @return the file or folder, or null if no tree has it
     *
     * @since 1.0
     */
    public File resolveSourceForRead( String relativePath )
    {
        for ( File pkg : javaPackageRoots() ) {
            File file = new File( pkg, relativePath );
            if ( file.exists() ) {
                return file;
            }
        }
        return null;
    }

    /**
     * Returns every tree's copy of the specified Java source path that exists, Core first. The
     * same package folder ({@code tabs}, {@code codeutils}) exists in several trees.
     *
     * @param relativePath the path below {@code src/main/java/com/micatechnologies/minecraft/csm}
     *
     * @return the files or folders that exist
     *
     * @since 1.0
     */
    public List< File > resolveSourceAll( String relativePath )
    {
        List< File > found = new ArrayList<>();
        for ( File pkg : javaPackageRoots() ) {
            File file = new File( pkg, relativePath );
            if ( file.exists() ) {
                found.add( file );
            }
        }
        return found;
    }

    /**
     * Returns which tree the specified file lives in.
     *
     * @param file any file inside the repository
     *
     * @return the module name, or null if the file is in no tree
     *
     * @since 1.0
     */
    public String moduleOfFile( File file )
    {
        String path;
        try {
            path = file.getCanonicalPath();
        }
        catch ( IOException e ) {
            path = file.getAbsolutePath();
        }
        String best = null;
        int bestLength = -1;
        for ( Map.Entry< String, File > entry : trees.entrySet() ) {
            String treePath;
            try {
                treePath = entry.getValue().getCanonicalPath();
            }
            catch ( IOException e ) {
                treePath = entry.getValue().getAbsolutePath();
            }
            if ( path.startsWith( treePath + File.separator ) && treePath.length() > bestLength ) {
                best = entry.getKey();
                bestLength = treePath.length();
            }
        }
        return best;
    }

    /**
     * Returns the blockstate file for the specified registry name, in whichever tree holds it.
     *
     * @param registryName the block's registry name
     *
     * @return the blockstate file, or null if no tree has one
     *
     * @since 1.0
     */
    public File blockstateFile( String registryName )
    {
        return resolveAssetForRead( "blockstates/" + registryName + ".json" );
    }

    /**
     * Returns every registry name that has a blockstate file in any tree.
     *
     * @return the registry names
     *
     * @since 1.0
     */
    public Set< String > knownBlockstates()
    {
        Set< String > names = new LinkedHashSet<>();
        for ( File dir : assetDirs( "blockstates" ) ) {
            String[] files = dir.list();
            if ( files == null ) {
                continue;
            }
            Arrays.sort( files );
            for ( String name : files ) {
                if ( name.endsWith( ".json" ) ) {
                    names.add( name.substring( 0, name.length() - ".json".length() ) );
                }
            }
        }
        return names;
    }

    /**
     * Returns the module that owns the specified block or item registry name, i.e. the tree its
     * blockstate, model, textures and lang line belong in.
     *
     * <p>Resolution order: the tree holding the blockstate (authoritative once the block exists),
     * then the tree holding the creative tab that registers the block, then the tree holding the
     * block's Java class. Core is the answer for anything still unresolved, because Core is the
     * only jar guaranteed to be installed.
     *
     * @param registryName the block's or item's registry name
     *
     * @return the module name, never null
     *
     * @since 1.0
     */
    public String ownerOf( String registryName )
    {
        File blockstate = blockstateFile( registryName );
        if ( blockstate != null ) {
            String module = moduleOfFile( blockstate );
            if ( module != null ) {
                return module;
            }
        }
        String owner = ownerByRegistryName().get( registryName );
        return owner != null ? owner : CORE;
    }

    /**
     * Returns the module that registers the specified registry name, ignoring where its assets
     * currently sit: the tree holding the creative tab it is registered in, or failing that the
     * tree holding its Java class. This is what {@link #ownerOf(String)} falls back to, and what
     * a tool generating a brand new asset should ask.
     *
     * @param registryName the block's or item's registry name
     *
     * @return the module name, or null if nothing registers that name
     *
     * @since 1.0
     */
    public String ownerFromRegistration( String registryName )
    {
        return ownerByRegistryName().get( registryName );
    }

    /**
     * Returns the module whose Java tree declares the specified class.
     *
     * @param simpleClassName the class's simple name, e.g. {@code BlockFireAlarmHorn}
     *
     * @return the module name, or null if no tree declares it
     *
     * @since 1.0
     */
    public String moduleOfClass( String simpleClassName )
    {
        SourceClass info = classes().get( simpleClassName );
        return info != null ? info.module : null;
    }

    /**
     * Returns what the source scan found out about the specified class.
     *
     * @param simpleClassName the class's simple name
     *
     * @return the scan result, or null if no tree declares the class
     *
     * @since 1.0
     */
    public SourceClass sourceClass( String simpleClassName )
    {
        return classes().get( simpleClassName );
    }

    /**
     * Returns every class the source scan found, across every tree.
     *
     * @return simple class name to scan result
     *
     * @since 1.0
     */
    public Map< String, SourceClass > classes()
    {
        if ( classes == null ) {
            classes = scanSources();
        }
        return classes;
    }

    /**
     * Returns the module whose {@code sounds.json} declares the specified sound event, i.e. the
     * tree the {@code .ogg} belongs in.
     *
     * @param soundName the sound event name, as it appears in {@code sounds.json}
     *
     * @return the module name, or null if no tree declares it
     *
     * @since 1.0
     */
    public String ownerOfSound( String soundName )
    {
        if ( ownerBySoundName == null ) {
            ownerBySoundName = new HashMap<>();
            for ( File soundsJson : assetFiles( "sounds.json" ) ) {
                String module = moduleOfFile( soundsJson );
                for ( String event : topLevelJsonKeys( readFileQuietly( soundsJson ) ) ) {
                    ownerBySoundName.putIfAbsent( event, module );
                }
            }
        }
        return ownerBySoundName.get( soundName );
    }

    /**
     * Returns every {@code sounds.json} in the repository, Core first. There is one per module
     * that registers a sound; the game merges them.
     *
     * @return the sounds.json files
     *
     * @since 1.0
     */
    public List< File > soundsJsonFiles()
    {
        return assetFiles( "sounds.json" );
    }

    /**
     * Returns every {@code .lang} file for the specified locale, Core first.
     *
     * @param locale the locale, e.g. {@code en_us}
     *
     * @return the lang files
     *
     * @since 1.0
     */
    public List< File > langFiles( String locale )
    {
        return assetFiles( "lang/" + locale + ".lang" );
    }

    /**
     * Returns every {@code .lang} file in every tree, Core first, in locale order within a tree.
     *
     * @return the lang files
     *
     * @since 1.0
     */
    public List< File > allLangFiles()
    {
        List< File > files = new ArrayList<>();
        for ( File dir : assetDirs( "lang" ) ) {
            File[] contents = dir.listFiles();
            if ( contents == null ) {
                continue;
            }
            Arrays.sort( contents );
            for ( File file : contents ) {
                if ( file.isFile() && file.getName().endsWith( ".lang" ) ) {
                    files.add( file );
                }
            }
        }
        return files;
    }

    /**
     * Returns every {@code CsmTab*.java} in every tree, sorted by file name so the report order
     * does not depend on which module a tab ended up in.
     *
     * @return the tab source files
     *
     * @since 1.0
     */
    public List< File > tabSourceFiles()
    {
        List< File > files = new ArrayList<>();
        for ( File dir : resolveSourceAll( "tabs" ) ) {
            File[] contents = dir.listFiles();
            if ( contents == null ) {
                continue;
            }
            for ( File file : contents ) {
                if ( file.isFile() && file.getName().startsWith( "CsmTab" )
                        && file.getName().endsWith( ".java" ) ) {
                    files.add( file );
                }
            }
        }
        files.sort( ( a, b ) -> a.getName().compareToIgnoreCase( b.getName() ) );
        return files;
    }

    /**
     * Walks every tree's Java sources and returns every {@code .java} file, Core first.
     *
     * @return the Java source files
     *
     * @since 1.0
     */
    public List< File > allJavaSourceFiles()
    {
        List< File > files = new ArrayList<>();
        for ( File pkg : javaPackageRoots() ) {
            collectFiles( pkg, ".java", files );
        }
        return files;
    }

    /**
     * Collects every file below the specified folder whose name ends with the specified suffix.
     *
     * @param folder the folder to walk
     * @param suffix the file name suffix to match, or "" for every file
     * @param into   the list to add to
     *
     * @since 1.0
     */
    public static void collectFiles( File folder, String suffix, List< File > into )
    {
        if ( !folder.isDirectory() ) {
            return;
        }
        try ( Stream< Path > walk = Files.walk( folder.toPath() ) ) {
            walk.filter( Files::isRegularFile )
                .filter( p -> suffix.isEmpty()
                        || p.getFileName().toString().toLowerCase( Locale.ROOT )
                            .endsWith( suffix.toLowerCase( Locale.ROOT ) ) )
                .sorted()
                .forEach( p -> into.add( p.toFile() ) );
        }
        catch ( IOException e ) {
            System.err.println( "Unable to walk " + folder + ": " + e.getMessage() );
        }
    }

    /**
     * Scans every tree's Java sources for the facts the tools need about each class.
     *
     * @return simple class name to scan result
     *
     * @since 1.0
     */
    private Map< String, SourceClass > scanSources()
    {
        Map< String, SourceClass > found = new LinkedHashMap<>();
        for ( File pkg : javaPackageRoots() ) {
            String module = moduleOfFile( pkg );
            List< File > sources = new ArrayList<>();
            collectFiles( pkg, ".java", sources );
            for ( File source : sources ) {
                String className
                        = source.getName().substring( 0, source.getName().length() - ".java".length() );
                String text = normalize( readFileQuietly( source ) );
                Matcher block = REGISTRY_NAME_RE.matcher( text );
                Matcher item = ITEM_REGISTRY_NAME_RE.matcher( text );
                Matcher extendsMatch = Pattern.compile( "class\\s+" + Pattern.quote( className )
                                                                + "\\s+extends\\s+(\\w+)" )
                                              .matcher( text );
                Map< String, String > constants = new LinkedHashMap<>();
                Matcher holder = HOLDER_CONST_RE.matcher( text );
                while ( holder.find() ) {
                    constants.put( holder.group( 1 ), holder.group( 2 ) );
                }
                String relative = relativePath( pkg, source.getParentFile() );
                found.putIfAbsent( className,
                                   new SourceClass( module, source, relative,
                                                    block.find() ? block.group( 1 ) : null,
                                                    item.find() ? item.group( 1 ) : null,
                                                    extendsMatch.find() ? extendsMatch.group( 1 )
                                                            : null,
                                                    text.contains( "extends AbstractBlockSetBasic" ),
                                                    constants ) );
            }
        }
        return found;
    }

    /**
     * Builds the registry name to owning module map by reading every tree's tab sources. A tab
     * class lives in the module that ships its blocks, so the tab file's own tree is the answer
     * for everything it registers.
     *
     * @return registry name to module name
     *
     * @since 1.0
     */
    private Map< String, String > ownerByRegistryName()
    {
        if ( ownerByRegistryName != null ) {
            return ownerByRegistryName;
        }
        Map< String, String > owners = new HashMap<>();
        Map< String, SourceClass > sources = classes();
        for ( File tabFile : tabSourceFiles() ) {
            String module = moduleOfFile( tabFile );
            String text = normalize( readFileQuietly( tabFile ) );

            Matcher byClass = TAB_CLASS_RE.matcher( text );
            while ( byClass.find() ) {
                addByClass( owners, sources, byClass.group( 1 ), module );
            }
            // initTabBlockIfLoaded names its class as a string precisely because that class
            // ships in a different module from the tab: the class's own tree is the owner.
            Matcher byIfLoaded = TAB_CLASS_IF_LOADED_RE.matcher( text );
            while ( byIfLoaded.find() ) {
                String named = byIfLoaded.group( 1 );
                SourceClass info = sources.get( named.substring( named.lastIndexOf( '.' ) + 1 ) );
                addByClass( owners, sources, named, info != null ? info.module : module );
            }
            Matcher byCtor = TAB_CTOR_RE.matcher( text );
            while ( byCtor.find() ) {
                if ( byCtor.group( 2 ) != null ) {
                    owners.putIfAbsent( byCtor.group( 2 ), module );
                }
                else {
                    addByClass( owners, sources, byCtor.group( 1 ), module );
                }
            }
            Matcher byConst = TAB_CONST_RE.matcher( text );
            while ( byConst.find() ) {
                SourceClass holder = sources.get( byConst.group( 1 ) );
                if ( holder != null ) {
                    String registry = holder.constants.get( byConst.group( 2 ) );
                    if ( registry != null ) {
                        owners.putIfAbsent( registry, module );
                    }
                }
            }
        }
        // Anything the tabs never named still has a home: the tree that declares its class.
        for ( SourceClass info : sources.values() ) {
            if ( info.blockRegistryName != null ) {
                owners.putIfAbsent( info.blockRegistryName, info.module );
            }
            if ( info.itemRegistryName != null ) {
                owners.putIfAbsent( info.itemRegistryName, info.module );
            }
        }
        ownerByRegistryName = owners;
        return owners;
    }

    /**
     * Records the owner of the registry name(s) a tab entry resolves to through its class.
     *
     * @param owners  the map being built
     * @param sources the source scan
     * @param name    the class name named in the tab, possibly fully qualified
     * @param module  the module the tab file lives in
     *
     * @since 1.0
     */
    private static void addByClass( Map< String, String > owners,
                                    Map< String, SourceClass > sources, String name,
                                    String module )
    {
        String simple = name.substring( name.lastIndexOf( '.' ) + 1 );
        SourceClass info = sources.get( simple );
        if ( info == null ) {
            return;
        }
        if ( info.blockRegistryName != null ) {
            owners.putIfAbsent( info.blockRegistryName, module );
            if ( info.blockSet ) {
                for ( String suffix : BLOCK_SET_SUFFIXES ) {
                    owners.putIfAbsent( info.blockRegistryName + suffix, module );
                }
            }
        }
        if ( info.itemRegistryName != null ) {
            owners.putIfAbsent( info.itemRegistryName, module );
        }
    }

    /**
     * Returns the names declared by a sound enum, i.e. the {@code "name"} in every
     * {@code CONSTANT("name")} entry.
     *
     * @param soundEnumFile the sound enum source file
     *
     * @return the sound event names
     *
     * @since 1.0
     */
    public static List< String > soundNamesIn( File soundEnumFile )
    {
        List< String > names = new ArrayList<>();
        Matcher matcher = SOUND_CONST_RE.matcher( readFileQuietly( soundEnumFile ) );
        while ( matcher.find() ) {
            names.add( matcher.group( 2 ) );
        }
        return names;
    }

    /**
     * Returns the top-level object keys of a JSON document, without a JSON parser: the tool that
     * needs this only wants the sound event names and must not fail on a comment or a trailing
     * comma.
     *
     * @param json the JSON text
     *
     * @return the top-level keys
     *
     * @since 1.0
     */
    private static List< String > topLevelJsonKeys( String json )
    {
        List< String > keys = new ArrayList<>();
        int depth = 0;
        boolean inString = false;
        boolean escaped = false;
        StringBuilder current = new StringBuilder();
        for ( int i = 0; i < json.length(); i++ ) {
            char c = json.charAt( i );
            if ( inString ) {
                if ( escaped ) {
                    escaped = false;
                }
                else if ( c == '\\' ) {
                    escaped = true;
                }
                else if ( c == '"' ) {
                    inString = false;
                    if ( depth == 1 ) {
                        // A key is a string at depth 1 followed by a colon.
                        int j = i + 1;
                        while ( j < json.length() && Character.isWhitespace( json.charAt( j ) ) ) {
                            j++;
                        }
                        if ( j < json.length() && json.charAt( j ) == ':' ) {
                            keys.add( current.toString() );
                        }
                    }
                }
                else {
                    current.append( c );
                }
                continue;
            }
            if ( c == '"' ) {
                inString = true;
                current.setLength( 0 );
            }
            else if ( c == '{' || c == '[' ) {
                depth++;
            }
            else if ( c == '}' || c == ']' ) {
                depth--;
            }
        }
        return keys;
    }

    /**
     * Returns the path of the specified file relative to the specified root, as a dotted Java
     * package name.
     *
     * @param root the root folder
     * @param file the folder below it
     *
     * @return the dotted package name, or "" for the root itself
     *
     * @since 1.0
     */
    private static String relativePath( File root, File file )
    {
        String rootPath = root.getAbsolutePath();
        String filePath = file.getAbsolutePath();
        if ( filePath.length() <= rootPath.length() ) {
            return "";
        }
        return filePath.substring( rootPath.length() + 1 ).replace( File.separatorChar, '.' );
    }

    /**
     * Collapses all whitespace so the source-scanning patterns can ignore formatting.
     *
     * @param text the text to normalize
     *
     * @return the text with every whitespace run replaced by one space
     *
     * @since 1.0
     */
    private static String normalize( String text )
    {
        return text.replaceAll( "\\s+", " " );
    }

    /**
     * Reads a file as UTF-8, returning "" rather than throwing: the tools scan whatever is on
     * disk and one unreadable file must not stop the report.
     *
     * @param file the file to read
     *
     * @return the file contents, or "" if it could not be read
     *
     * @since 1.0
     */
    public static String readFileQuietly( File file )
    {
        try {
            return new String( Files.readAllBytes( file.toPath() ), StandardCharsets.UTF_8 );
        }
        catch ( IOException e ) {
            return "";
        }
    }

    /**
     * Returns an unmodifiable view of the module name to tree folder mapping, Core first.
     *
     * @return the trees
     *
     * @since 1.0
     */
    public Map< String, File > trees()
    {
        return Collections.unmodifiableMap( trees );
    }
}
