package com.micatechnologies.minecraft.csm.trafficaccessories;

/**
 * Where the parts of an arrow board are, in 1/16 block units.
 *
 * <p>Generated by {@code dev-env-utils/scripts/gen_work_zone_devices.py} -- do not hand
 * edit. The chassis is a baked model and everything above it is drawn by
 * {@link TileEntityArrowBoardRenderer}; these are the numbers both are built from, so the
 * drawn mast meets the modelled trailer instead of floating over it.</p>
 *
 * @version 1.0
 * @since 2026.9
 */
public final class ArrowBoardGeometry {

  /** Lamp columns across the panel. */
  public static final int GRID_COLS = 7;

  /** Lamp rows down the panel. */
  public static final int GRID_ROWS = 5;

  /** mast x0, in 1/16 block units. */
  public static final float MAST_X0 = 1.9100f;

  /** mast x1, in 1/16 block units. */
  public static final float MAST_X1 = 14.0900f;

  /** mast half, in 1/16 block units. */
  public static final float MAST_HALF = 1.7640f;

  /** mast y0, in 1/16 block units. */
  public static final float MAST_Y0 = 4.4100f;

  /** mast y1, in 1/16 block units. */
  public static final float MAST_Y1 = 46.2000f;

  /** brace y0, in 1/16 block units. */
  public static final float BRACE_Y0 = 26.8800f;

  /** brace y1, in 1/16 block units. */
  public static final float BRACE_Y1 = 40.3200f;

  /** brace half y, in 1/16 block units. */
  public static final float BRACE_HALF_Y = 1.2600f;

  /** panel x0, in 1/16 block units. */
  public static final float PANEL_X0 = -20.5600f;

  /** panel x1, in 1/16 block units. */
  public static final float PANEL_X1 = 36.5600f;

  /** panel y0, in 1/16 block units. */
  public static final float PANEL_Y0 = 43.6800f;

  /** panel y1, in 1/16 block units. */
  public static final float PANEL_Y1 = 72.2400f;

  /** panel z0, in 1/16 block units. */
  public static final float PANEL_Z0 = 5.0600f;

  /** panel z1, in 1/16 block units. */
  public static final float PANEL_Z1 = 9.6800f;

  /** lit x0, in 1/16 block units. */
  public static final float LIT_X0 = -18.7960f;

  /** lit y0, in 1/16 block units. */
  public static final float LIT_Y0 = 45.4440f;

  /** cell w, in 1/16 block units. */
  public static final float CELL_W = 7.6560f;

  /** cell h, in 1/16 block units. */
  public static final float CELL_H = 5.0064f;

  /** lamp radius, in 1/16 block units. */
  public static final float LAMP_RADIUS = 1.7022f;

  private ArrowBoardGeometry() {
    throw new AssertionError("ArrowBoardGeometry is constants only");
  }
}
