package com.micatechnologies.minecraft.csm.trafficaccessories;

/**
 * Where the parts of a barricade are, in 1/16 block units.
 *
 * <p>Generated by {@code dev-env-utils/scripts/gen_work_zone_devices.py} -- do not hand
 * edit. The rails and uprights are a baked model and the warning lights and mounted signs
 * are drawn over them by {@link TileEntityBarricadeRenderer}; these are the numbers both
 * are built from.</p>
 *
 * @version 1.0
 * @since 2026.9
 */
public final class BarricadeGeometry {

  /** left upright x, in 1/16 block units. */
  public static final float LEFT_UPRIGHT_X = 0.0000f;

  /** right upright x, in 1/16 block units. */
  public static final float RIGHT_UPRIGHT_X = 16.0000f;

  /** rail half z, in 1/16 block units. */
  public static final float RAIL_HALF_Z = 0.4732f;

  /** rail centre z, in 1/16 block units. */
  public static final float RAIL_CENTRE_Z = 8.0000f;

  /** type1 top, in 1/16 block units. */
  public static final float TYPE1_TOP = 17.4720f;

  /** type3 top, in 1/16 block units. */
  public static final float TYPE3_TOP = 24.0240f;

  /** leg half x, in 1/16 block units. */
  public static final float LEG_HALF_X = 1.0010f;

  /** folding left upright x, in 1/16 block units. */
  public static final float FOLDING_LEFT_UPRIGHT_X = 2.8000f;

  /** folding right upright x, in 1/16 block units. */
  public static final float FOLDING_RIGHT_UPRIGHT_X = 13.2000f;

  /** folding rail half z, in 1/16 block units. */
  public static final float FOLDING_RAIL_HALF_Z = 0.3000f;

  /** folding rail centre z, in 1/16 block units. */
  public static final float FOLDING_RAIL_CENTRE_Z = 5.2100f;

  /** folding top, in 1/16 block units. */
  public static final float FOLDING_TOP = 14.8500f;

  private BarricadeGeometry() {
    throw new AssertionError("BarricadeGeometry is constants only");
  }
}
