package com.micatechnologies.minecraft.csm.trafficaccessories;

/**
 * Where the parts of a barricade are, in 1/16 block units.
 *
 * <p>Generated by {@code dev-env-utils/scripts/gen_work_zone_devices.py} -- do not hand
 * edit. The rails and uprights are a baked model and the warning lights and mounted signs
 * are drawn over them by {@link TileEntityBarricadeRenderer}; these are the numbers both
 * are built from.</p>
 *
 * @version 1.0
 * @since 2026.9
 */
public final class BarricadeGeometry {

  /** left upright x, in 1/16 block units. */
  public static final float LEFT_UPRIGHT_X = 0.0000f;

  /** right upright x, in 1/16 block units. */
  public static final float RIGHT_UPRIGHT_X = 16.0000f;

  /** rail half z, in 1/16 block units. */
  public static final float RAIL_HALF_Z = 0.3510f;

  /** type1 top, in 1/16 block units. */
  public static final float TYPE1_TOP = 12.9600f;

  /** type3 top, in 1/16 block units. */
  public static final float TYPE3_TOP = 17.8200f;

  /** leg half x, in 1/16 block units. */
  public static final float LEG_HALF_X = 0.7425f;

  private BarricadeGeometry() {
    throw new AssertionError("BarricadeGeometry is constants only");
  }
}
