package com.micatechnologies.minecraft.csm.trafficaccessories;

/**
 * The mast arm curve sizes, and the exact block cells each one occupies.
 *
 * <p><b>Generated by {@code dev-env-utils/scripts/gen_mast_arm_curves.py}. Do not edit by
 * hand.</b> The cell lists here are the same lists the generator split the OBJ geometry on. If
 * the two ever disagreed, a curve would place a block with no model in it, or draw a slice of
 * tube in mid-air with no block behind it -- so they are emitted together from one source.
 *
 * <p>Each cell is {@code {alongArm, up}} in blocks from the placed root, before the block's
 * facing rotation is applied. The list is ordered from the pole outward and is face-connected,
 * so consecutive cells always share a face.
 */
public enum MastArmCurveProfile {

  /**
   * Local Street upsweep: 4 of run, 1 of rise, leaving the pole at 26.6 degrees, across
   * 5 block cells.
   */
  P4X1(4, 1,
      new int[][]{{0, 0}, {1, 0}, {1, 1}, {2, 1}, {3, 1}},
      new double[][]{{0.18472D, 0.08070D, 0.00000D, 0.81528D, 1.00000D, 1.00000D},
          {0.22188D, 0.67708D, 0.73625D, 0.77812D, 1.00000D, 1.00000D},
          {0.22348D, 0.00000D, 0.00000D, 0.77652D, 0.51073D, 0.92060D},
          {0.23125D, 0.00000D, 0.00000D, 0.76875D, 0.69487D, 1.00000D},
          {0.24062D, 0.18013D, 0.00061D, 0.75938D, 0.75033D, 1.00000D}}),
  /**
   * Collector upsweep: 5 of run, 1 of rise, leaving the pole at 21.8 degrees, across
   * 6 block cells.
   */
  P5X1(5, 1,
      new int[][]{{0, 0}, {1, 0}, {1, 1}, {2, 1}, {3, 1}, {4, 1}},
      new double[][]{{0.18528D, 0.10905D, 0.00000D, 0.81472D, 1.00000D, 1.00000D},
          {0.22000D, 0.59332D, 0.46028D, 0.78000D, 1.00000D, 1.00000D},
          {0.22348D, 0.00000D, 0.00000D, 0.77652D, 0.40498D, 0.61079D},
          {0.22750D, 0.00000D, 0.00000D, 0.77250D, 0.60167D, 1.00000D},
          {0.23500D, 0.07833D, 0.00000D, 0.76500D, 0.71668D, 1.00000D},
          {0.24250D, 0.20332D, 0.00061D, 0.75750D, 0.75034D, 1.00000D}}),
  /**
   * Arterial upsweep: 6 of run, 2 of rise, leaving the pole at 33.7 degrees, across
   * 8 block cells.
   */
  P6X2(6, 2,
      new int[][]{{0, 0}, {0, 1}, {1, 1}, {2, 1}, {3, 1}, {3, 2}, {4, 2}, {5, 2}},
      new double[][]{{0.18565D, 0.03371D, 0.05491D, 0.81435D, 1.00000D, 1.00000D},
          {0.21752D, 0.00000D, 0.00000D, 0.78248D, 0.35697D, 0.33739D},
          {0.21875D, 0.00000D, 0.00000D, 0.78125D, 0.86241D, 1.00000D},
          {0.22500D, 0.35981D, 0.00000D, 0.77500D, 1.00000D, 1.00000D},
          {0.23125D, 0.74504D, 0.83397D, 0.76875D, 1.00000D, 1.00000D},
          {0.23177D, 0.00000D, 0.00000D, 0.76823D, 0.53403D, 0.99936D},
          {0.23750D, 0.02153D, 0.00000D, 0.76250D, 0.69913D, 1.00000D},
          {0.24375D, 0.18976D, 0.00061D, 0.75625D, 0.75012D, 1.00000D}}),
  /**
   * Major Intersection upsweep: 8 of run, 2 of rise, leaving the pole at 26.6 degrees, across
   * 10 block cells.
   */
  P8X2(8, 2,
      new int[][]{{0, 0}, {1, 0}, {1, 1}, {2, 1}, {3, 1}, {4, 1}, {4, 2}, {5, 2}, {6, 2}, {7, 2}},
      new double[][]{{0.18612D, 0.08447D, 0.00000D, 0.81388D, 1.00000D, 1.00000D},
          {0.21719D, 0.70965D, 0.81596D, 0.78281D, 1.00000D, 1.00000D},
          {0.21752D, 0.00000D, 0.00000D, 0.78248D, 0.63542D, 1.00000D},
          {0.22188D, 0.11458D, 0.00000D, 0.77812D, 0.97974D, 1.00000D},
          {0.22656D, 0.45776D, 0.00000D, 0.77344D, 1.00000D, 1.00000D},
          {0.23125D, 0.73927D, 0.85286D, 0.76875D, 1.00000D, 1.00000D},
          {0.23164D, 0.00000D, 0.00000D, 0.76836D, 0.47829D, 0.98047D},
          {0.23594D, 0.00000D, 0.00000D, 0.76406D, 0.63237D, 1.00000D},
          {0.24062D, 0.11763D, 0.00000D, 0.75938D, 0.72294D, 1.00000D},
          {0.24531D, 0.21456D, 0.00062D, 0.75469D, 0.75017D, 1.00000D}}),
  /**
   * Wide Arterial upsweep: 10 of run, 2 of rise, leaving the pole at 21.8 degrees, across
   * 12 block cells.
   */
  P10X2(10, 2,
      new int[][]{{0, 0}, {1, 0}, {1, 1}, {2, 1}, {3, 1}, {4, 1}, {5, 1}, {5, 2}, {6, 2}, {7, 2}, {8, 2}, {9, 2}},
      new double[][]{{0.18640D, 0.11127D, 0.00000D, 0.81360D, 1.00000D, 1.00000D},
          {0.21625D, 0.61302D, 0.56779D, 0.78375D, 1.00000D, 1.00000D},
          {0.21752D, 0.00000D, 0.00000D, 0.78248D, 0.48668D, 0.75272D},
          {0.22000D, 0.00000D, 0.00000D, 0.78000D, 0.78602D, 1.00000D},
          {0.22375D, 0.25398D, 0.00000D, 0.77625D, 1.00000D, 1.00000D},
          {0.22750D, 0.51502D, 0.00000D, 0.77250D, 1.00000D, 1.00000D},
          {0.23125D, 0.73647D, 0.86487D, 0.76875D, 1.00000D, 1.00000D},
          {0.23156D, 0.00000D, 0.00000D, 0.76844D, 0.44167D, 0.96847D},
          {0.23500D, 0.00000D, 0.00000D, 0.76500D, 0.57939D, 1.00000D},
          {0.23875D, 0.06061D, 0.00000D, 0.76125D, 0.67668D, 1.00000D},
          {0.24250D, 0.16332D, 0.00000D, 0.75750D, 0.73355D, 1.00000D},
          {0.24625D, 0.22645D, 0.00062D, 0.75375D, 0.75017D, 1.00000D}});

  private final int run;
  private final int rise;
  private final int[][] cells;
  private final double[][] boxes;

  MastArmCurveProfile(int run, int rise, int[][] cells, double[][] boxes) {
    this.run = run;
    this.rise = rise;
    this.cells = cells;
    this.boxes = boxes;
  }

  /**
   * The horizontal distance the curve covers, in blocks.
   *
   * @return the run in blocks
   */
  public int getRun() {
    return run;
  }

  /**
   * The vertical distance the curve climbs, in blocks.
   *
   * @return the rise in blocks
   */
  public int getRise() {
    return rise;
  }

  /**
   * The number of block cells this curve occupies, including the root.
   *
   * @return the cell count
   */
  public int getCellCount() {
    return cells.length;
  }

  /**
   * Bits of a mount mask. Model space, as the curve is drawn facing north with the arm running
   * toward -Z; the blockstate's y rotation carries them round with the block, so model EAST is
   * {@code facing.rotateY()} in the world and model WEST is {@code facing.rotateYCCW()}.
   */
  public static final int MOUNT_DOWN = 1;

  /**
   * @see #MOUNT_DOWN
   */
  public static final int MOUNT_UP = 2;

  /**
   * @see #MOUNT_DOWN
   */
  public static final int MOUNT_EAST = 4;

  /**
   * @see #MOUNT_DOWN
   */
  public static final int MOUNT_WEST = 8;

  /**
   * How many shape values one cell accounts for -- one per mount mask.
   */
  public static final int SHAPE_STRIDE = 16;

  /**
   * Packs a cell index and a mount mask into the single {@code shape} property value the
   * blockstate keys its model and its stub submodels off.
   *
   * <p>One property rather than five is forced, not preferred. A stub model depends on both the
   * cell and the direction, so a mount property would have to carry the cell index; four such
   * properties beside cell and facing come to 1,370,928 block states, and Minecraft builds every
   * one of them eagerly. This packing is 768 -- the same as four plain booleans would have cost.
   *
   * @param cell      the cell index
   * @param mountMask any of {@link #MOUNT_DOWN}, {@link #MOUNT_UP}, {@link #MOUNT_EAST},
   *                  {@link #MOUNT_WEST}, or-ed together
   *
   * @return the packed shape value
   */
  public static int shapeIndex(int cell, int mountMask) {
    return cell * SHAPE_STRIDE + mountMask;
  }

  /**
   * The offset of one cell from the root, as {@code {alongArm, up}} in blocks, unrotated.
   *
   * @param index the cell index, {@code 0} being the root at the pole
   *
   * @return a two-element offset; callers must not mutate it
   */
  public int[] getCellOffset(int index) {
    return cells[index];
  }

  /**
   * The measured extent of one cell's tube slice inside its own block, as
   * {@code {minX, minY, minZ, maxX, maxY, maxZ}} in 0..1, for the unrotated (facing north)
   * orientation. Measured off the emitted mesh rather than guessed, and clamped to the block:
   * geometry that overhangs into the next cell is covered by that cell's own box, because every
   * cell of a curve is a real placed block.
   *
   * @param index the cell index, {@code 0} being the root at the pole
   *
   * @return a six-element box; callers must not mutate it
   */
  public double[] getCellBox(int index) {
    return boxes[index];
  }

  /**
   * The number of distinct {@code shape} values this profile can take: one per cell per mount
   * mask.
   *
   * @return the shape count
   */
  public int getShapeCount() {
    return cells.length * SHAPE_STRIDE;
  }
}
