package com.micatechnologies.minecraft.csm.trafficaccessories;

/**
 * Where a portable signal trailer's boom is, cell by cell, in 1/16 block units.
 *
 * <p>Generated by {@code dev-env-utils/scripts/gen_work_zone_devices.py} -- do not hand
 * edit.</p>
 *
 * <p>The boom is not a block. It is geometry belonging to a trailer up to eight cells
 * away, so a mount kit that wants to clamp to it cannot probe the world for it and has to
 * be told. These are the same numbers the boom is swept from, which is what stops the
 * clamp drifting off the bar the next time the boom is reshaped.</p>
 *
 * <p>Coordinates are in the frame of the CELL the boom passes through: the bar is centred
 * on the cell across the boom's run, and its underside is that cell's floor.</p>
 *
 * @version 1.0
 * @since 2026.9
 */
public final class SignalTrailerGeometry {

  /** Registry name of the trailer style that carries a boom. */
  public static final String ARM_TRAILER = "portable_signal_trailer_arm";

  /** Cells above the trailer's own block that the boom's level run sits at. */
  public static final int BOOM_HEIGHT = 8;

  /** First cell out from the trailer that the LEVEL run covers; nearer cells are the rise. */
  public static final int FIRST_CELL = 3;

  /** Last cell out from the trailer that the level run covers. */
  public static final int LAST_CELL = 8;

  /** Half the bar's width, per cell from {@link #FIRST_CELL}. The boom tapers. */
  public static final float[] HALF_WIDTH = {1.9292f, 1.7875f, 1.6458f, 1.5042f, 1.3625f, 1.2208f};

  /** The bar's depth above the cell floor, per cell from {@link #FIRST_CELL}. */
  public static final float[] THICKNESS = {4.0667f, 3.8000f, 3.5333f, 3.2667f, 3.0000f, 2.7333f};

  /** True if {@code cell} is a cell the level run covers. */
  public static boolean isLevelRunCell(int cell) {
    return cell >= FIRST_CELL && cell <= LAST_CELL;
  }

  /** Half the bar's width at {@code cell}; the nearest covered cell if it is out of range. */
  public static float halfWidthAt(int cell) {
    return HALF_WIDTH[clampIndex(cell)];
  }

  /** The bar's depth above the cell floor at {@code cell}, clamped the same way. */
  public static float thicknessAt(int cell) {
    return THICKNESS[clampIndex(cell)];
  }

  private static int clampIndex(int cell) {
    int index = cell - FIRST_CELL;
    if (index < 0) {
      return 0;
    }
    if (index >= HALF_WIDTH.length) {
      return HALF_WIDTH.length - 1;
    }
    return index;
  }

  private SignalTrailerGeometry() {
    throw new AssertionError("SignalTrailerGeometry is constants only");
  }
}
