/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.csm;

import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.common.network.simpleimpl.IMessageHandler;
import net.minecraftforge.fml.common.network.simpleimpl.IMessage;
import net.minecraftforge.fml.common.network.IGuiHandler;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.discovery.ASMDataTable;
import net.minecraftforge.fml.common.IWorldGenerator;
import net.minecraftforge.fml.common.IFuelHandler;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.client.event.ModelRegistryEvent;

import net.minecraft.world.storage.WorldSavedData;
import net.minecraft.world.gen.IChunkGenerator;
import net.minecraft.world.chunk.IChunkProvider;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.World;
import net.minecraft.util.ResourceLocation;
import net.minecraft.potion.Potion;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Item;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.Random;
import java.util.List;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class Elementscsm implements IFuelHandler, IWorldGenerator {
	protected final List<ModElement> elements = new ArrayList<>();
	protected final List<Supplier<Block>> blocks = new ArrayList<>();
	protected final List<Supplier<Item>> items = new ArrayList<>();
	protected final List<Supplier<Biome>> biomes = new ArrayList<>();
	protected final List<Supplier<EntityEntry>> entities = new ArrayList<>();
	protected final List<Supplier<Potion>> potions = new ArrayList<>();

	public void preInit(FMLPreInitializationEvent event) {
		try {
			for (ASMDataTable.ASMData asmData : event.getAsmData().getAll(ModElement.Tag.class.getName())) {
				Class<?> clazz = Class.forName(asmData.getClassName());
				if (clazz.getSuperclass() == Elementscsm.ModElement.class)
					elements.add((Elementscsm.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(Elementscsm.ModElement::initElements);
		this.addNetworkMessage(csmVariables.WorldSavedDataSyncMessageHandler.class, csmVariables.WorldSavedDataSyncMessage.class, Side.SERVER,
				Side.CLIENT);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		ResourceLocation sound0 = new ResourceLocation("csm", "bell");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound0).setRegistryName(sound0));
		ResourceLocation sound1 = new ResourceLocation("csm", "codetector");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound1).setRegistryName(sound1));
		ResourceLocation sound2 = new ResourceLocation("csm", "et70_chime");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound2).setRegistryName(sound2));
		ResourceLocation sound3 = new ResourceLocation("csm", "handdryer");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound3).setRegistryName(sound3));
		ResourceLocation sound4 = new ResourceLocation("csm", "marchtime_as");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound4).setRegistryName(sound4));
		ResourceLocation sound5 = new ResourceLocation("csm", "mills_firealarm");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound5).setRegistryName(sound5));
		ResourceLocation sound6 = new ResourceLocation("csm", "mt_code3");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound6).setRegistryName(sound6));
		ResourceLocation sound7 = new ResourceLocation("csm", "nest_test");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound7).setRegistryName(sound7));
		ResourceLocation sound8 = new ResourceLocation("csm", "panasonicfan");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound8).setRegistryName(sound8));
		ResourceLocation sound9 = new ResourceLocation("csm", "2910calcode");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound9).setRegistryName(sound9));
		ResourceLocation sound10 = new ResourceLocation("csm", "4030code44");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound10).setRegistryName(sound10));
		ResourceLocation sound11 = new ResourceLocation("csm", "smokealarm");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound11).setRegistryName(sound11));
		ResourceLocation sound12 = new ResourceLocation("csm", "spectralert");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound12).setRegistryName(sound12));
		ResourceLocation sound13 = new ResourceLocation("csm", "wheelockas");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound13).setRegistryName(sound13));
		ResourceLocation sound14 = new ResourceLocation("csm", "adaptabell");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound14).setRegistryName(sound14));
		ResourceLocation sound15 = new ResourceLocation("csm", "bell2");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound15).setRegistryName(sound15));
		ResourceLocation sound16 = new ResourceLocation("csm", "firebell");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound16).setRegistryName(sound16));
		ResourceLocation sound17 = new ResourceLocation("csm", "kac");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound17).setRegistryName(sound17));
		ResourceLocation sound18 = new ResourceLocation("csm", "svenew");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound18).setRegistryName(sound18));
		ResourceLocation sound19 = new ResourceLocation("csm", "sveold");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound19).setRegistryName(sound19));
		ResourceLocation sound20 = new ResourceLocation("csm", "sven");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound20).setRegistryName(sound20));
		ResourceLocation sound21 = new ResourceLocation("csm", "sveo");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound21).setRegistryName(sound21));
		ResourceLocation sound22 = new ResourceLocation("csm", "wheelock7002t");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound22).setRegistryName(sound22));
		ResourceLocation sound23 = new ResourceLocation("csm", "dingblock");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound23).setRegistryName(sound23));
		ResourceLocation sound24 = new ResourceLocation("csm", "est_genesis");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound24).setRegistryName(sound24));
		ResourceLocation sound25 = new ResourceLocation("csm", "est_integrity");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound25).setRegistryName(sound25));
		ResourceLocation sound26 = new ResourceLocation("csm", "lms_voice_evac");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound26).setRegistryName(sound26));
		ResourceLocation sound27 = new ResourceLocation("csm", "stahorn");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound27).setRegistryName(sound27));
		ResourceLocation sound28 = new ResourceLocation("csm", "7002t_medspeed");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound28).setRegistryName(sound28));
		ResourceLocation sound29 = new ResourceLocation("csm", "7002t_slowspeed");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound29).setRegistryName(sound29));
		ResourceLocation sound30 = new ResourceLocation("csm", "edwards_adaptahorn_code44");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound30).setRegistryName(sound30));
		ResourceLocation sound31 = new ResourceLocation("csm", "gentex_gos_code3");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound31).setRegistryName(sound31));
		ResourceLocation sound32 = new ResourceLocation("csm", "sae_marchtime");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound32).setRegistryName(sound32));
		ResourceLocation sound33 = new ResourceLocation("csm", "simplex_4051_marchtime");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound33).setRegistryName(sound33));
		ResourceLocation sound34 = new ResourceLocation("csm", "broken_7002t");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound34).setRegistryName(sound34));
		ResourceLocation sound35 = new ResourceLocation("csm", "walksig_wait");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound35).setRegistryName(sound35));
		ResourceLocation sound36 = new ResourceLocation("csm", "mclalsve");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound36).setRegistryName(sound36));
		ResourceLocation sound37 = new ResourceLocation("csm", "edwards_io_reset");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound37).setRegistryName(sound37));
		ResourceLocation sound38 = new ResourceLocation("csm", "simplex_panel_reset");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound38).setRegistryName(sound38));
		ResourceLocation sound39 = new ResourceLocation("csm", "pullstation_pull");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound39).setRegistryName(sound39));
		ResourceLocation sound40 = new ResourceLocation("csm", "notifier_voice_evac");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound40).setRegistryName(sound40));
		ResourceLocation sound41 = new ResourceLocation("csm", "simplex_voice_evac_old_alt");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound41).setRegistryName(sound41));
		ResourceLocation sound42 = new ResourceLocation("csm", "PanelComponentAdded");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound42).setRegistryName(sound42));
		ResourceLocation sound43 = new ResourceLocation("csm", "notifier_voice_evac_alt");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound43).setRegistryName(sound43));
		ResourceLocation sound44 = new ResourceLocation("csm", "code3_bell");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound44).setRegistryName(sound44));
		ResourceLocation sound45 = new ResourceLocation("csm", "code44_bell");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound45).setRegistryName(sound45));
		ResourceLocation sound46 = new ResourceLocation("csm", "continuous_bell");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound46).setRegistryName(sound46));
		ResourceLocation sound47 = new ResourceLocation("csm", "marchtime_bell");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound47).setRegistryName(sound47));
		ResourceLocation sound48 = new ResourceLocation("csm", "elevator_dooropen");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound48).setRegistryName(sound48));
		ResourceLocation sound49 = new ResourceLocation("csm", "elevator_fan");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound49).setRegistryName(sound49));
		ResourceLocation sound50 = new ResourceLocation("csm", "mcla_tornado_evac");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound50).setRegistryName(sound50));
		ResourceLocation sound51 = new ResourceLocation("csm", "new_simplex_beep");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound51).setRegistryName(sound51));
		ResourceLocation sound52 = new ResourceLocation("csm", "power_linked");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound52).setRegistryName(sound52));
		ResourceLocation sound53 = new ResourceLocation("csm", "power_unlinked");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound53).setRegistryName(sound53));
		ResourceLocation sound54 = new ResourceLocation("csm", "sp_switch_off");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound54).setRegistryName(sound54));
		ResourceLocation sound55 = new ResourceLocation("csm", "sp_switch_on");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound55).setRegistryName(sound55));
		ResourceLocation sound56 = new ResourceLocation("csm", "standard_switch_off");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound56).setRegistryName(sound56));
		ResourceLocation sound57 = new ResourceLocation("csm", "standard_switch_on");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound57).setRegistryName(sound57));
		ResourceLocation sound58 = new ResourceLocation("csm", "tl_switch_off");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound58).setRegistryName(sound58));
		ResourceLocation sound59 = new ResourceLocation("csm", "tl_switch_on");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound59).setRegistryName(sound59));
		ResourceLocation sound60 = new ResourceLocation("csm", "ups_lowbatt");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound60).setRegistryName(sound60));
		ResourceLocation sound61 = new ResourceLocation("csm", "ups_silence");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound61).setRegistryName(sound61));
		ResourceLocation sound62 = new ResourceLocation("csm", "oldradio");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound62).setRegistryName(sound62));
		ResourceLocation sound63 = new ResourceLocation("csm", "asteroids_cabinet");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound63).setRegistryName(sound63));
		ResourceLocation sound64 = new ResourceLocation("csm", "bz_cabinet");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound64).setRegistryName(sound64));
		ResourceLocation sound65 = new ResourceLocation("csm", "cp_cabinet");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound65).setRegistryName(sound65));
		ResourceLocation sound66 = new ResourceLocation("csm", "galaga_cabinet");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound66).setRegistryName(sound66));
		ResourceLocation sound67 = new ResourceLocation("csm", "miscmd_cabinet");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound67).setRegistryName(sound67));
		ResourceLocation sound68 = new ResourceLocation("csm", "pacman_cabinet");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound68).setRegistryName(sound68));
		ResourceLocation sound69 = new ResourceLocation("csm", "tempest_cabinet");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound69).setRegistryName(sound69));
		ResourceLocation sound70 = new ResourceLocation("csm", "oldrecordplayer2");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound70).setRegistryName(sound70));
		ResourceLocation sound71 = new ResourceLocation("csm", "locker_door_close");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound71).setRegistryName(sound71));
		ResourceLocation sound72 = new ResourceLocation("csm", "locker_door_open");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound72).setRegistryName(sound72));
		ResourceLocation sound73 = new ResourceLocation("csm", "oldrecordplayer");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound73).setRegistryName(sound73));
		ResourceLocation sound74 = new ResourceLocation("csm", "awful_notifier_ve");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound74).setRegistryName(sound74));
		ResourceLocation sound75 = new ResourceLocation("csm", "notifier_voice_evac_alt2");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound75).setRegistryName(sound75));
		ResourceLocation sound76 = new ResourceLocation("csm", "notifier_tornado_voice_evac");
		event.getRegistry().register(new net.minecraft.util.SoundEvent(sound76).setRegistryName(sound76));
	}

	@Override
	public void generate(Random random, int chunkX, int chunkZ, World world, IChunkGenerator cg, IChunkProvider cp) {
		elements.forEach(element -> element.generateWorld(random, chunkX * 16, chunkZ * 16, world, world.provider.getDimension(), cg, cp));
	}

	@Override
	public int getBurnTime(ItemStack fuel) {
		for (ModElement element : elements) {
			int ret = element.addFuel(fuel);
			if (ret != 0)
				return ret;
		}
		return 0;
	}

	@SubscribeEvent
	public void onPlayerLoggedIn(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerLoggedInEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData mapdata = csmVariables.MapVariables.get(event.player.world);
			WorldSavedData worlddata = csmVariables.WorldVariables.get(event.player.world);
			if (mapdata != null)
				csm.PACKET_HANDLER.sendTo(new csmVariables.WorldSavedDataSyncMessage(0, mapdata), (EntityPlayerMP) event.player);
			if (worlddata != null)
				csm.PACKET_HANDLER.sendTo(new csmVariables.WorldSavedDataSyncMessage(1, worlddata), (EntityPlayerMP) event.player);
		}
	}

	@SubscribeEvent
	public void onPlayerChangedDimension(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerChangedDimensionEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData worlddata = csmVariables.WorldVariables.get(event.player.world);
			if (worlddata != null)
				csm.PACKET_HANDLER.sendTo(new csmVariables.WorldSavedDataSyncMessage(1, worlddata), (EntityPlayerMP) event.player);
		}
	}
	private int messageID = 0;

	public <T extends IMessage, V extends IMessage> void addNetworkMessage(Class<? extends IMessageHandler<T, V>> handler, Class<T> messageClass,
			Side... sides) {
		for (Side side : sides)
			csm.PACKET_HANDLER.registerMessage(handler, messageClass, messageID, side);
		messageID++;
	}

	public static class GuiHandler implements IGuiHandler {
		@Override
		public Object getServerGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			return null;
		}

		@Override
		public Object getClientGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			return null;
		}
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<Biome>> getBiomes() {
		return biomes;
	}

	public List<Supplier<EntityEntry>> getEntities() {
		return entities;
	}

	public List<Supplier<Potion>> getPotions() {
		return potions;
	}

	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final Elementscsm elements;
		protected final int sortid;

		public ModElement(Elementscsm elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLInitializationEvent event) {
		}

		public void preInit(FMLPreInitializationEvent event) {
		}

		public void generateWorld(Random random, int posX, int posZ, World world, int dimID, IChunkGenerator cg, IChunkProvider cp) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		public void registerModels(ModelRegistryEvent event) {
		}

		public int addFuel(ItemStack fuel) {
			return 0;
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
