package com.micatechnologies.minecraft.csm.trafficaccessories;

/**
 * The mast arm curve sizes, and the exact block cells each one occupies.
 *
 * <p><b>Generated by {@code dev-env-utils/scripts/gen_mast_arm_curves.py}. Do not edit by
 * hand.</b> The cell lists here are the same lists the generator split the OBJ geometry on. If
 * the two ever disagreed, a curve would place a block with no model in it, or draw a slice of
 * tube in mid-air with no block behind it -- so they are emitted together from one source.
 *
 * <p>Each cell is {@code {alongArm, up}} in blocks from the placed root, before the block's
 * facing rotation is applied. The list is ordered from the pole outward and is face-connected,
 * so consecutive cells always share a face.
 */
public enum MastArmCurveProfile {

  /**
   * Local Street upsweep: 4 of run, 1 of rise, leaving the pole at 26.6 degrees, across
   * 5 block cells.
   */
  P4X1(4, 1,
      new int[][]{{0, 0}, {1, 0}, {1, 1}, {2, 1}, {3, 1}},
      new double[][]{{0.11250D, 0.06142D, 0.00000D, 0.88750D, 1.00000D, 1.00000D},
          {0.20312D, 0.65953D, 0.73036D, 0.79688D, 1.00000D, 1.00000D},
          {0.20581D, 0.00000D, 0.00000D, 0.79419D, 0.52285D, 0.92649D},
          {0.21875D, 0.00000D, 0.00000D, 0.78125D, 0.70107D, 1.00000D},
          {0.23438D, 0.17393D, 0.00061D, 0.76562D, 0.75085D, 1.00000D}}),
  /**
   * Collector upsweep: 5 of run, 1 of rise, leaving the pole at 21.8 degrees, across
   * 6 block cells.
   */
  P5X1(5, 1,
      new int[][]{{0, 0}, {1, 0}, {1, 1}, {2, 1}, {3, 1}, {4, 1}},
      new double[][]{{0.11250D, 0.08843D, 0.00000D, 0.88750D, 1.00000D, 1.00000D},
          {0.20000D, 0.57427D, 0.45546D, 0.80000D, 1.00000D, 1.00000D},
          {0.20581D, 0.00000D, 0.00000D, 0.79419D, 0.41956D, 0.61560D},
          {0.21250D, 0.00000D, 0.00000D, 0.78750D, 0.61155D, 1.00000D},
          {0.22500D, 0.06845D, 0.00000D, 0.77500D, 0.72166D, 1.00000D},
          {0.23750D, 0.19834D, 0.00061D, 0.76250D, 0.75095D, 1.00000D}}),
  /**
   * Arterial upsweep: 6 of run, 2 of rise, leaving the pole at 33.7 degrees, across
   * 8 block cells.
   */
  P6X2(6, 2,
      new int[][]{{0, 0}, {0, 1}, {1, 1}, {2, 1}, {3, 1}, {3, 2}, {4, 2}, {5, 2}},
      new double[][]{{0.11250D, 0.00979D, 0.04409D, 0.88750D, 1.00000D, 1.00000D},
          {0.19587D, 0.00000D, 0.00000D, 0.80413D, 0.37518D, 0.34822D},
          {0.19792D, 0.00000D, 0.00000D, 0.80208D, 0.87764D, 1.00000D},
          {0.20833D, 0.34458D, 0.00000D, 0.79167D, 1.00000D, 1.00000D},
          {0.21875D, 0.73318D, 0.83023D, 0.78125D, 1.00000D, 1.00000D},
          {0.21962D, 0.00000D, 0.00000D, 0.78038D, 0.54216D, 1.00000D},
          {0.22917D, 0.01339D, 0.00000D, 0.77083D, 0.70327D, 1.00000D},
          {0.23958D, 0.18562D, 0.00061D, 0.76042D, 0.75047D, 1.00000D}}),
  /**
   * Major Intersection upsweep: 8 of run, 2 of rise, leaving the pole at 26.6 degrees, across
   * 10 block cells.
   */
  P8X2(8, 2,
      new int[][]{{0, 0}, {1, 0}, {1, 1}, {2, 1}, {3, 1}, {4, 1}, {4, 2}, {5, 2}, {6, 2}, {7, 2}},
      new double[][]{{0.11250D, 0.06706D, 0.00000D, 0.88750D, 1.00000D, 1.00000D},
          {0.19531D, 0.68961D, 0.80736D, 0.80469D, 1.00000D, 1.00000D},
          {0.19587D, 0.00000D, 0.00000D, 0.80413D, 0.65297D, 1.00000D},
          {0.20312D, 0.09703D, 0.00000D, 0.79688D, 0.99465D, 1.00000D},
          {0.21094D, 0.44285D, 0.00000D, 0.78906D, 1.00000D, 1.00000D},
          {0.21875D, 0.72715D, 0.84995D, 0.78125D, 1.00000D, 1.00000D},
          {0.21940D, 0.00000D, 0.00000D, 0.78060D, 0.48750D, 0.98339D},
          {0.22656D, 0.00000D, 0.00000D, 0.77344D, 0.63857D, 1.00000D},
          {0.23438D, 0.11143D, 0.00000D, 0.76562D, 0.72606D, 1.00000D},
          {0.24219D, 0.21144D, 0.00062D, 0.75781D, 0.75043D, 1.00000D}}),
  /**
   * Wide Arterial upsweep: 10 of run, 2 of rise, leaving the pole at 21.8 degrees, across
   * 12 block cells.
   */
  P10X2(10, 2,
      new int[][]{{0, 0}, {1, 0}, {1, 1}, {2, 1}, {3, 1}, {4, 1}, {5, 1}, {5, 2}, {6, 2}, {7, 2}, {8, 2}, {9, 2}},
      new double[][]{{0.11250D, 0.08843D, 0.00000D, 0.88750D, 1.00000D, 1.00000D},
          {0.19375D, 0.59185D, 0.56071D, 0.80625D, 1.00000D, 1.00000D},
          {0.19587D, 0.00000D, 0.00000D, 0.80413D, 0.50573D, 0.75980D},
          {0.20000D, 0.00000D, 0.00000D, 0.80000D, 0.80287D, 1.00000D},
          {0.20625D, 0.23713D, 0.00000D, 0.79375D, 1.00000D, 1.00000D},
          {0.21250D, 0.50044D, 0.00000D, 0.78750D, 1.00000D, 1.00000D},
          {0.21875D, 0.72421D, 0.86249D, 0.78125D, 1.00000D, 1.00000D},
          {0.21927D, 0.00000D, 0.00000D, 0.78073D, 0.45155D, 0.97084D},
          {0.22500D, 0.00000D, 0.00000D, 0.77500D, 0.58684D, 1.00000D},
          {0.23125D, 0.05316D, 0.00000D, 0.76875D, 0.68166D, 1.00000D},
          {0.23750D, 0.15834D, 0.00000D, 0.76250D, 0.73605D, 1.00000D},
          {0.24375D, 0.22395D, 0.00062D, 0.75625D, 0.75048D, 1.00000D}});

  private final int run;
  private final int rise;
  private final int[][] cells;
  private final double[][] boxes;

  MastArmCurveProfile(int run, int rise, int[][] cells, double[][] boxes) {
    this.run = run;
    this.rise = rise;
    this.cells = cells;
    this.boxes = boxes;
  }

  /**
   * The horizontal distance the curve covers, in blocks.
   *
   * @return the run in blocks
   */
  public int getRun() {
    return run;
  }

  /**
   * The vertical distance the curve climbs, in blocks.
   *
   * @return the rise in blocks
   */
  public int getRise() {
    return rise;
  }

  /**
   * The number of block cells this curve occupies, including the root.
   *
   * @return the cell count
   */
  public int getCellCount() {
    return cells.length;
  }

  /**
   * The offset of one cell from the root, as {@code {alongArm, up}} in blocks, unrotated.
   *
   * @param index the cell index, {@code 0} being the root at the pole
   *
   * @return a two-element offset; callers must not mutate it
   */
  public int[] getCellOffset(int index) {
    return cells[index];
  }

  /**
   * The measured extent of one cell's tube slice inside its own block, as
   * {@code {minX, minY, minZ, maxX, maxY, maxZ}} in 0..1, for the unrotated (facing north)
   * orientation. Measured off the emitted mesh rather than guessed, and clamped to the block:
   * geometry that overhangs into the next cell is covered by that cell's own box, because every
   * cell of a curve is a real placed block.
   *
   * @param index the cell index, {@code 0} being the root at the pole
   *
   * @return a six-element box; callers must not mutate it
   */
  public double[] getCellBox(int index) {
    return boxes[index];
  }
}
