#!/usr/bin/env python3
"""Build an index of every CSM block: registry name, source package, base class and creative tab.

This is the shared data source for the recipe generator (``gen_block_recipes.py``) and anything
else that needs to reason about the whole block set. It reads the Java sources rather than the
running game, because the game has no dump command and the sources are authoritative for all
three facts we need.

Two kinds of registration exist in the tab files and both are handled:

    initTabBlock(BlockFoo.class, event)          -> registry name comes from BlockFoo's
                                                    getBlockRegistryName()
    initTabBlock(new BlockTrafficSign("foo"))    -> registry name is the constructor argument

``AbstractBlockSetBasic`` subclasses additionally produce ``<name>_fence``, ``<name>_slab`` and
``<name>_stairs`` variants, which are expanded here so the index matches the blockstates on disk.
"""

import os
import re

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
SRC_ROOT = os.path.join(REPO_ROOT, "src", "main", "java", "com", "micatechnologies",
                        "minecraft", "csm")
TABS_DIR = os.path.join(SRC_ROOT, "tabs")
BLOCKSTATE_DIR = os.path.join(REPO_ROOT, "src", "main", "resources", "assets", "csm",
                              "blockstates")

# Variants generated by AbstractBlockSetBasic for each set block.
BLOCK_SET_SUFFIXES = ("_fence", "_slab", "_stairs")

_REGISTRY_NAME_RE = re.compile(
    r'public\s+String\s+getBlockRegistryName\(\)\s*\{\s*return\s*"([^"]+)"\s*;')
_EXTENDS_RE = re.compile(r'class\s+(\w+)\s+extends\s+(\w+)')
# Class literals, which may be written fully qualified:
#     initTabBlock(BlockFoo.class, event)
#     initTabBlock(com.micatechnologies.minecraft.csm.pkg.BlockFoo.class, event)
_TAB_CLASS_RE = re.compile(r'initTabBlock\(\s*([\w.]+)\.class')
# Constructor calls, with or without a registry name argument:
#     initTabBlock(new BlockTrafficSign("foo"))
#     initTabBlock(new BlockTrafficLightMountKit())
_TAB_CTOR_RE = re.compile(r'initTabBlock\(\s*new\s+([\w.]+)\s*\(\s*(?:"([^"]+)")?')
# Pre-built instances held as constants on a holder class:
#     initTabBlock(TrafficSignalBlocks.FOO_SIGNAL)
_TAB_CONST_RE = re.compile(r'initTabBlock\(\s*(\w+)\.(\w+)\s*\)')
_TAB_ID_RE = re.compile(r'public\s+String\s+getTabId\(\)\s*\{\s*return\s*"([^"]+)"\s*;')

# Holder classes such as TrafficSignalBlocks declare pre-built block instances as constants:
#     public static final BlockControllableSignal FOO_SIGNAL =
#         new BlockControllableSignal.Builder("registryname", ...)
# Tabs then register them as initTabBlock(TrafficSignalBlocks.FOO_SIGNAL).
_HOLDER_CONST_RE = re.compile(
    r'public\s+static\s+final\s+\w+\s+(\w+)\s*=\s*new\s+[\w.]+\(\s*"([^"]+)"')


def _normalize(text):
    """Collapse all whitespace so the regexes above can ignore source formatting."""
    return re.sub(r"\s+", " ", text)


def scan_sources():
    """Return {class_name: {"registry": str|None, "package": str, "extends": str|None}}."""
    classes = {}
    for dirpath, _dirnames, filenames in os.walk(SRC_ROOT):
        for filename in filenames:
            if not filename.endswith(".java"):
                continue
            path = os.path.join(dirpath, filename)
            with open(path, "r", encoding="utf-8", errors="replace") as handle:
                text = _normalize(handle.read())
            class_name = filename[:-5]
            registry = _REGISTRY_NAME_RE.search(text)
            extends = None
            for match in _EXTENDS_RE.finditer(text):
                if match.group(1) == class_name:
                    extends = match.group(2)
                    break
            package = os.path.relpath(dirpath, SRC_ROOT).replace(os.sep, ".")
            classes[class_name] = {
                "registry": registry.group(1) if registry else None,
                "package": "" if package == "." else package,
                "extends": extends,
                "is_block_set": "extends AbstractBlockSetBasic" in text,
                "constants": {m.group(1): m.group(2)
                              for m in _HOLDER_CONST_RE.finditer(text)},
            }
    return classes


def scan_tabs():
    """Return {tab_id: [(registry_name, class_name), ...]} for every block in every tab."""
    classes = scan_sources()
    tabs = {}
    for filename in sorted(os.listdir(TABS_DIR)):
        if not filename.startswith("CsmTab") or not filename.endswith(".java"):
            continue
        path = os.path.join(TABS_DIR, filename)
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            text = _normalize(handle.read())
        # CsmTabNone is the hidden catch-all and returns null from getTabId(), so it has no
        # string id to scrape. Give it a synthetic one derived from the class name so its blocks
        # are still indexed (they are excluded from recipes, but must be accounted for).
        tab_id_match = _TAB_ID_RE.search(text)
        if tab_id_match:
            tab_id = tab_id_match.group(1)
        else:
            tab_id = "tab" + filename[len("CsmTab"):-len(".java")].lower()
        entries = []

        def add_by_class(qualified_name):
            """Resolve a (possibly fully qualified) class name to its registry name(s)."""
            class_name = qualified_name.rsplit(".", 1)[-1]
            info = classes.get(class_name)
            if not info or not info["registry"]:
                entries.append((None, class_name))
                return
            entries.append((info["registry"], class_name))
            if info["is_block_set"]:
                for suffix in BLOCK_SET_SUFFIXES:
                    entries.append((info["registry"] + suffix, class_name))

        for match in _TAB_CLASS_RE.finditer(text):
            add_by_class(match.group(1))

        for match in _TAB_CTOR_RE.finditer(text):
            qualified_name, explicit = match.group(1), match.group(2)
            if explicit:
                entries.append((explicit, qualified_name.rsplit(".", 1)[-1]))
            else:
                # No-arg constructor: the class supplies its own registry name.
                add_by_class(qualified_name)

        for match in _TAB_CONST_RE.finditer(text):
            holder, constant = match.group(1), match.group(2)
            info = classes.get(holder)
            if not info:
                entries.append((None, "{0}.{1}".format(holder, constant)))
                continue
            registry = info["constants"].get(constant)
            entries.append((registry, holder) if registry
                           else (None, "{0}.{1}".format(holder, constant)))

        tabs[tab_id] = entries
    return tabs, classes


def known_blockstates():
    """Return the set of registry names that have a blockstate file on disk."""
    return {name[:-5] for name in os.listdir(BLOCKSTATE_DIR) if name.endswith(".json")}


def build_index():
    """Return (index, tabs, classes) where index maps registry name -> descriptor dict."""
    tabs, classes = scan_tabs()
    index = {}
    for tab_id, entries in tabs.items():
        for registry, class_name in entries:
            if registry is None:
                continue
            info = classes.get(class_name, {})
            index[registry] = {
                "tab": tab_id,
                "class": class_name,
                "package": info.get("package", ""),
                "extends": info.get("extends"),
            }
    return index, tabs, classes


def main():
    index, tabs, classes = build_index()
    states = known_blockstates()

    print("Blocks indexed from tabs : {0}".format(len(index)))
    print("Blockstate files on disk : {0}".format(len(states)))
    print()
    print("Per tab:")
    for tab_id in sorted(tabs):
        resolved = [r for r, _ in tabs[tab_id] if r]
        unresolved = [c for r, c in tabs[tab_id] if not r]
        note = "  ({0} unresolved)".format(len(unresolved)) if unresolved else ""
        print("  {0:28s} {1:4d}{2}".format(tab_id, len(resolved), note))
        for class_name in sorted(set(unresolved)):
            print("        unresolved: {0}".format(class_name))

    missing_state = sorted(r for r in index if r not in states)
    orphan_state = sorted(s for s in states if s not in index)
    print()
    print("Indexed but no blockstate file : {0}".format(len(missing_state)))
    for name in missing_state[:15]:
        print("    {0}".format(name))
    print("Blockstate file but not indexed: {0}".format(len(orphan_state)))
    for name in orphan_state[:15]:
        print("    {0}".format(name))
    _ = classes


if __name__ == "__main__":
    main()
