#!/usr/bin/env python3
"""Build an index of every CSM block: registry name, source package, base class and creative tab.

This is the shared data source for the recipe generator (``gen_block_recipes.py``) and anything
else that needs to reason about the whole block set. It reads the Java sources rather than the
running game, because the game has no dump command and the sources are authoritative for all
three facts we need.

The mod is built from several source trees: Core at ``src/main`` plus one per optional module
under ``modules/<name>/src/main`` (see ``modules.gradle``). Every tree contributes tab classes,
block classes and blockstate files to the same ``csm`` namespace, so the index scans all of them
and reports the same totals the game does. ``module_of_source`` / ``module_of_blockstate`` say
which tree a file came from, which is what the asset partitioning tooling needs.

Two kinds of registration exist in the tab files and both are handled:

    initTabBlock(BlockFoo.class, event)          -> registry name comes from BlockFoo's
                                                    getBlockRegistryName()
    initTabBlock(new BlockTrafficSign("foo"))    -> registry name is the constructor argument

``AbstractBlockSetBasic`` subclasses additionally produce ``<name>_fence``, ``<name>_slab`` and
``<name>_stairs`` variants, which are expanded here so the index matches the blockstates on disk.

Blocks registered with ``initTabBlockIfLoaded``/``initTabItemIfLoaded`` name their class as a
string so the owning tab does not have to import an optional module. Those are resolved too, by
the class's simple name.
"""

import os
import re

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))

# The Java package every source tree shares below its src/main/java root.
_JAVA_PACKAGE = os.path.join("com", "micatechnologies", "minecraft", "csm")

# Core's source tree. Kept as a module-level name because it predates the module split and
# other scripts import it; prefer ``source_roots()`` for anything that must see every module.
SRC_ROOT = os.path.join(REPO_ROOT, "src", "main", "java", _JAVA_PACKAGE)
TABS_DIR = os.path.join(SRC_ROOT, "tabs")
BLOCKSTATE_DIR = os.path.join(REPO_ROOT, "src", "main", "resources", "assets", "csm",
                              "blockstates")

MODULES_DIR = os.path.join(REPO_ROOT, "modules")

# Variants generated by AbstractBlockSetBasic for each set block.
BLOCK_SET_SUFFIXES = ("_fence", "_slab", "_stairs")

_REGISTRY_NAME_RE = re.compile(
    r'public\s+String\s+getBlockRegistryName\(\)\s*\{\s*return\s*"([^"]+)"\s*;')
_ITEM_REGISTRY_NAME_RE = re.compile(
    r'public\s+String\s+getItemRegistryName\(\)\s*\{\s*return\s*"([^"]+)"\s*;')
_EXTENDS_RE = re.compile(r'class\s+(\w+)\s+extends\s+(\w+)')
# Class literals, which may be written fully qualified:
#     initTabBlock(BlockFoo.class, event)
#     initTabBlock(com.micatechnologies.minecraft.csm.pkg.BlockFoo.class, event)
_TAB_CLASS_RE = re.compile(r'initTabBlock\(\s*([\w.]+)\.class')
# Constructor calls, with or without a registry name argument:
#     initTabBlock(new BlockTrafficSign("foo"))
#     initTabBlock(new BlockTrafficLightMountKit())
_TAB_CTOR_RE = re.compile(r'initTabBlock\(\s*new\s+([\w.]+)\s*\(\s*(?:"([^"]+)")?')
# Pre-built instances held as constants on a holder class:
#     initTabBlock(TrafficSignalBlocks.FOO_SIGNAL)
_TAB_CONST_RE = re.compile(r'initTabBlock\(\s*(\w+)\.(\w+)\s*\)')
# Optional-module registration, where the class is named as a string so the tab need not
# import a module that depends on it:
#     initTabBlockIfLoaded("csm_tts", "com...csm.tts.BlockRedstoneTTS", event)
_TAB_CLASS_IF_LOADED_RE = re.compile(
    r'initTabBlockIfLoaded\(\s*"[^"]*"\s*,\s*"([\w.]+)"')
_TAB_ID_RE = re.compile(r'public\s+String\s+getTabId\(\)\s*\{\s*return\s*"([^"]+)"\s*;')

# Item registrations, mirroring the block ones above.
_TAB_ITEM_CLASS_RE = re.compile(r'initTabItem\(\s*([\w.]+)\.class')
_TAB_ITEM_CTOR_RE = re.compile(r'initTabItem\(\s*new\s+([\w.]+)\s*\(\s*(?:"([^"]+)")?')
_TAB_ITEM_CLASS_IF_LOADED_RE = re.compile(
    r'initTabItemIfLoaded\(\s*"[^"]*"\s*,\s*"([\w.]+)"')

# Holder classes such as TrafficSignalBlocks declare pre-built block instances as constants:
#     public static final BlockControllableSignal FOO_SIGNAL =
#         new BlockControllableSignal.Builder("registryname", ...)
# Tabs then register them as initTabBlock(TrafficSignalBlocks.FOO_SIGNAL).
_HOLDER_CONST_RE = re.compile(
    r'public\s+static\s+final\s+\w+\s+(\w+)\s*=\s*new\s+[\w.]+\(\s*"([^"]+)"')


def module_names():
    """Return the optional module directory names, sorted, or [] before the split."""
    if not os.path.isdir(MODULES_DIR):
        return []
    return sorted(name for name in os.listdir(MODULES_DIR)
                  if os.path.isdir(os.path.join(MODULES_DIR, name, "src", "main")))


def source_roots():
    """Return [(module, java_root)] for Core and every module that has Java sources.

    ``module`` is ``"core"`` for ``src/main`` and the module directory name otherwise.
    """
    roots = []
    if os.path.isdir(SRC_ROOT):
        roots.append(("core", SRC_ROOT))
    for name in module_names():
        path = os.path.join(MODULES_DIR, name, "src", "main", "java", _JAVA_PACKAGE)
        if os.path.isdir(path):
            roots.append((name, path))
    return roots


def resource_roots():
    """Return [(module, assets/csm dir)] for Core and every module that has resources."""
    roots = []
    core = os.path.join(REPO_ROOT, "src", "main", "resources", "assets", "csm")
    if os.path.isdir(core):
        roots.append(("core", core))
    for name in module_names():
        path = os.path.join(MODULES_DIR, name, "src", "main", "resources", "assets", "csm")
        if os.path.isdir(path):
            roots.append((name, path))
    return roots


def blockstate_dirs():
    """Return [(module, blockstates dir)] for every tree that has one."""
    dirs = []
    for module, assets in resource_roots():
        path = os.path.join(assets, "blockstates")
        if os.path.isdir(path):
            dirs.append((module, path))
    return dirs


def tab_dirs():
    """Return [(module, tabs dir)] for every tree that has one."""
    dirs = []
    for module, root in source_roots():
        path = os.path.join(root, "tabs")
        if os.path.isdir(path):
            dirs.append((module, path))
    return dirs


def lang_files(locale="en_us"):
    """Return every ``assets/csm/lang/<locale>.lang`` path, Core first then the modules.

    The game merges a domain's lang files across every jar that carries them, so anything
    reading display names has to read all of them, not just Core's.
    """
    paths = []
    for _module, assets in resource_roots():
        path = os.path.join(assets, "lang", locale + ".lang")
        if os.path.isfile(path):
            paths.append(path)
    return paths


def blockstate_path(registry_name):
    """Return the path of ``<registry_name>.json`` in whichever tree holds it, or None."""
    for _module, directory in blockstate_dirs():
        path = os.path.join(directory, registry_name + ".json")
        if os.path.isfile(path):
            return path
    return None


def module_of_blockstate(registry_name):
    """Return the module whose tree holds ``<registry_name>.json``, or None."""
    for module, directory in blockstate_dirs():
        if os.path.isfile(os.path.join(directory, registry_name + ".json")):
            return module
    return None


def _normalize(text):
    """Collapse all whitespace so the regexes above can ignore source formatting."""
    return re.sub(r"\s+", " ", text)


def scan_sources():
    """Return {class_name: {"registry": str|None, "package": str, "extends": str|None, ...}}.

    Every source tree is scanned. ``module`` names the tree the class came from and ``package``
    stays relative to that tree's ``...minecraft.csm`` root, so it reads the same as before the
    module split.
    """
    classes = {}
    for module, root in source_roots():
        for dirpath, _dirnames, filenames in os.walk(root):
            for filename in filenames:
                if not filename.endswith(".java"):
                    continue
                path = os.path.join(dirpath, filename)
                with open(path, "r", encoding="utf-8", errors="replace") as handle:
                    text = _normalize(handle.read())
                class_name = filename[:-5]
                registry = _REGISTRY_NAME_RE.search(text)
                item_registry = _ITEM_REGISTRY_NAME_RE.search(text)
                extends = None
                for match in _EXTENDS_RE.finditer(text):
                    if match.group(1) == class_name:
                        extends = match.group(2)
                        break
                package = os.path.relpath(dirpath, root).replace(os.sep, ".")
                classes[class_name] = {
                    "registry": registry.group(1) if registry else None,
                    "item_registry": item_registry.group(1) if item_registry else None,
                    "package": "" if package == "." else package,
                    "extends": extends,
                    "module": module,
                    "is_block_set": "extends AbstractBlockSetBasic" in text,
                    "constants": {m.group(1): m.group(2)
                                  for m in _HOLDER_CONST_RE.finditer(text)},
                }
    return classes


def module_of_source(class_name, classes=None):
    """Return the module whose Java tree declares ``class_name``, or None."""
    if classes is None:
        classes = scan_sources()
    info = classes.get(class_name)
    return info.get("module") if info else None


def _tab_files():
    """Return [(module, tab_file_path)] for every CsmTab*.java in every tree, sorted by name."""
    files = []
    for module, directory in tab_dirs():
        for filename in sorted(os.listdir(directory)):
            if filename.startswith("CsmTab") and filename.endswith(".java"):
                files.append((module, os.path.join(directory, filename)))
    return sorted(files, key=lambda pair: os.path.basename(pair[1]))


def tab_files():
    """Return [(module, tab_file_path)] for every CsmTab*.java in every tree, sorted by name.

    A tab class lives in the module that ships its blocks, so the module here is also the owner
    of everything the tab registers -- which is what ``csm_layout`` builds ownership from.
    """
    return _tab_files()


def scan_tabs():
    """Return ({tab_id: [(registry_name, class_name), ...]}, classes) over every source tree."""
    classes = scan_sources()
    tabs = {}
    for _module, path in _tab_files():
        filename = os.path.basename(path)
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            text = _normalize(handle.read())
        # A hidden tab returns null from getTabId(), so it has no string id to scrape. Give
        # it a synthetic one derived from the class name so its blocks are still indexed (they
        # are excluded from recipes, but must be accounted for).
        tab_id_match = _TAB_ID_RE.search(text)
        if tab_id_match:
            tab_id = tab_id_match.group(1)
        else:
            tab_id = "tab" + filename[len("CsmTab"):-len(".java")].lower()
        entries = []

        def add_by_class(qualified_name):
            """Resolve a (possibly fully qualified) class name to its registry name(s)."""
            class_name = qualified_name.rsplit(".", 1)[-1]
            info = classes.get(class_name)
            if not info or not info["registry"]:
                entries.append((None, class_name))
                return
            entries.append((info["registry"], class_name))
            if info["is_block_set"]:
                for suffix in BLOCK_SET_SUFFIXES:
                    entries.append((info["registry"] + suffix, class_name))

        for match in _TAB_CLASS_RE.finditer(text):
            add_by_class(match.group(1))

        for match in _TAB_CLASS_IF_LOADED_RE.finditer(text):
            add_by_class(match.group(1))

        for match in _TAB_CTOR_RE.finditer(text):
            qualified_name, explicit = match.group(1), match.group(2)
            if explicit:
                entries.append((explicit, qualified_name.rsplit(".", 1)[-1]))
            else:
                # No-arg constructor: the class supplies its own registry name.
                add_by_class(qualified_name)

        for match in _TAB_CONST_RE.finditer(text):
            holder, constant = match.group(1), match.group(2)
            info = classes.get(holder)
            if not info:
                entries.append((None, "{0}.{1}".format(holder, constant)))
                continue
            registry = info["constants"].get(constant)
            entries.append((registry, holder) if registry
                           else (None, "{0}.{1}".format(holder, constant)))

        tabs[tab_id] = entries
    return tabs, classes


def scan_item_tabs():
    """Return {tab_id: [(registry_name, class_name), ...]} for every item in every tab.

    Mirrors :func:`scan_tabs` for ``initTabItem``. Items whose registry name is only known at
    runtime come back with ``None`` as the registry name.
    """
    classes = scan_sources()
    tabs = {}
    for _module, path in _tab_files():
        filename = os.path.basename(path)
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            text = _normalize(handle.read())
        tab_id_match = _TAB_ID_RE.search(text)
        tab_id = (tab_id_match.group(1) if tab_id_match
                  else "tab" + filename[len("CsmTab"):-len(".java")].lower())
        entries = []

        def add_by_class(qualified_name):
            class_name = qualified_name.rsplit(".", 1)[-1]
            info = classes.get(class_name) or {}
            registry = info.get("item_registry")
            entries.append((registry, class_name) if registry else (None, class_name))

        for match in _TAB_ITEM_CLASS_RE.finditer(text):
            add_by_class(match.group(1))
        for match in _TAB_ITEM_CLASS_IF_LOADED_RE.finditer(text):
            add_by_class(match.group(1))
        for match in _TAB_ITEM_CTOR_RE.finditer(text):
            qualified_name, explicit = match.group(1), match.group(2)
            if explicit:
                entries.append((explicit, qualified_name.rsplit(".", 1)[-1]))
            else:
                add_by_class(qualified_name)

        tabs[tab_id] = entries
    return tabs, classes


def known_blockstates():
    """Return the set of registry names that have a blockstate file on disk, in any tree."""
    names = set()
    for _module, directory in blockstate_dirs():
        names |= {name[:-5] for name in os.listdir(directory) if name.endswith(".json")}
    return names


def build_index():
    """Return (index, tabs, classes) where index maps registry name -> descriptor dict."""
    tabs, classes = scan_tabs()
    index = {}
    for tab_id, entries in tabs.items():
        for registry, class_name in entries:
            if registry is None:
                continue
            info = classes.get(class_name, {})
            index[registry] = {
                "tab": tab_id,
                "class": class_name,
                "package": info.get("package", ""),
                "extends": info.get("extends"),
                "module": info.get("module"),
            }
    return index, tabs, classes


def main():
    index, tabs, classes = build_index()
    states = known_blockstates()

    print("Source trees scanned      : {0}".format(
        ", ".join(module for module, _ in source_roots())))
    print("Blocks indexed from tabs : {0}".format(len(index)))
    print("Blockstate files on disk : {0}".format(len(states)))
    print()
    print("Per tab:")
    for tab_id in sorted(tabs):
        resolved = [r for r, _ in tabs[tab_id] if r]
        unresolved = [c for r, c in tabs[tab_id] if not r]
        note = "  ({0} unresolved)".format(len(unresolved)) if unresolved else ""
        print("  {0:28s} {1:4d}{2}".format(tab_id, len(resolved), note))
        for class_name in sorted(set(unresolved)):
            print("        unresolved: {0}".format(class_name))

    missing_state = sorted(r for r in index if r not in states)
    orphan_state = sorted(s for s in states if s not in index)
    print()
    print("Indexed but no blockstate file : {0}".format(len(missing_state)))
    for name in missing_state[:15]:
        print("    {0}".format(name))
    print("Blockstate file but not indexed: {0}".format(len(orphan_state)))
    for name in orphan_state[:15]:
        print("    {0}".format(name))
    _ = classes


if __name__ == "__main__":
    main()
