#!/usr/bin/env python3
"""
gen_large_custom_signs.py -- road signs whose plate is bigger than the block they are placed in.

Every other static sign plate fits inside its own block, give or take the half-block overhang a
JSON element allows. These do not: a 5 x 3 panel is 80 units wide, and a JSON block model element
may reach no further than -16..32 on any axis or the whole model silently fails to load. So the
plate is a Forge OBJ model instead, which has no such limit, and the sign stays one ordinary
``BlockTrafficSign`` -- the plate simply overhangs the neighbouring blocks, centred on the block
it was placed in both across and up and down.

For each sign in the catalogue this writes, into the Roads module's tree:

  * ``models/block/trafficsigns/<name>.obj``               -- plate on its post, ``shift=none``
  * ``models/block/trafficsigns/<name>_setback.obj``       -- the plate moved back 12.5 units onto
    a post that reaches the back of the block, where the other signs' setback models put theirs
  * ``models/block/trafficsigns/<name>_back_to_back.obj``  -- the plate moved back to sit against
    the partner sign's post, with no post of its own, like the other back-to-back models
  * ``models/block/trafficsigns/<name>.mtl``               -- ``face`` (the art) and ``back``
    (``absolutely_nothing_sign``, the back every other plate wears)
  * ``blockstates/<name>.json``                            -- facing / downward / shift, inventory

The plate is a closed box half a unit thick. Its front face carries the art, so any transparency
in the art (rounded corners) is see-through rather than showing the grey back behind it. The
front face is authored on model north: looking at a north face from outside puts +X on the
viewer's left, so texture u runs from x_max to x_min.

The face textures come from the user's own artwork, which is not in the repository. Pass
``--art DIR`` to rebuild them from the originals: each is trimmed to its opaque bounds, resampled
once to the PLATE's aspect and letterboxed, centred, in a square power-of-two texture (Minecraft
1.12 refuses a non-square texture that is not animated), with the art's edge pixels repeated out
to fill the rest; the front face's UVs pick out just the art's rectangle. It is not squished to
fill the square -- see ``art_rect`` for why that blurs. ``--check`` covers the models and
blockstates, whose UVs depend on the same layout, but not the textures.

Usage:
    python gen_large_custom_signs.py                 # write models and blockstates
    python gen_large_custom_signs.py --art <dir>     # ... and rebuild the face textures
    python gen_large_custom_signs.py --check         # exit 1 if the tree has drifted
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import csm_layout as layout  # noqa: E402

OWNER = layout.owner_of_folder("trafficsigns")
ROADS = layout.asset_dir_for_write(OWNER)
MODEL_DIR = os.path.join(ROADS, "models", "block", "trafficsigns")
BLOCKSTATE_DIR = os.path.join(ROADS, "blockstates")
TEXTURE_DIR = os.path.join(ROADS, "textures", "blocks", "trafficsigns")

MODEL_PREFIX = "csm:trafficsigns/"
BACK_TEXTURE = "csm:blocks/trafficsigns/absolutely_nothing_sign"
HEADER = "# Procedurally generated by dev-env-utils/scripts/gen_large_custom_signs.py -- do not hand edit"

# (registry name, source art file, width in blocks, height in blocks, texture size). The size is
# picked so the art gets at least ~128 px per block, a one-block sign's density, once it is
# letterboxed at the plate's aspect (see art_rect): 1024 gives the 5-wide panels 192 px a block,
# 512 gives the 3-wide one 149.
CATALOGUE = [
    ("danger_low_clearance_sign", "DANGER_LOW_CLEARANCE.png", 3, 2, 512),
    ("cars_only_banner_sign", "CARS_ONLY_FINAL.png", 5, 1, 1024),
    ("truckers_use_expressways_sign", "TruckersUseExpresswaysNotParkways.png", 5, 3, 1024),
]
# Pixels of edge-repeated padding kept around the art on every side of its texture: two texels
# still at mip level 4, the deepest Minecraft builds, so the plate's rim never averages in
# transparency or a neighbouring atlas sprite.
ART_PADDING = 32

PLATE_THICKNESS = 0.5
# The post every sign plate is bolted to: 1 x 3 units behind the plate, one block tall.
POST_X = (7.5, 8.5)
POST_DEPTH = 3.0
# Where the plate's front sits in each shift, matching the JSON plates' own setback (12.5) and
# back-to-back (28.5) models. Back-to-back is half a unit further forward than theirs, so the
# plate's back lands exactly on the partner's post face rather than overlapping it.
SHIFTS = {
    "none": {"front": 0.0, "post": True},
    "setback": {"front": 12.5, "post": True},
    "back_to_back": {"front": 28.0, "post": False},
}

FACINGS = [("n", 0), ("nw", 45), ("w", 90), ("sw", 135), ("s", 180), ("se", 225), ("e", 270),
           ("ne", 315)]


# --- mesh ----------------------------------------------------------------------------------------
class Mesh:
    """Triangles grouped by material, written as one OBJ in 0..1 block space."""

    def __init__(self):
        self.v, self.vt, self.vn = [], [], []
        self.groups = {}
        self._index = {}

    def _add(self, store, value):
        key = (id(store), tuple(round(c, 6) for c in value))
        if key not in self._index:
            store.append(value)
            self._index[key] = len(store)
        return self._index[key]

    def quad(self, material, corners, uvs, normal):
        """Four corners wound counter-clockwise seen from the side ``normal`` points to."""
        n = self._add(self.vn, normal)
        idx = [(self._add(self.v, p), self._add(self.vt, t), n) for p, t in zip(corners, uvs)]
        tris = self.groups.setdefault(material, [])
        tris.append([idx[0], idx[1], idx[2]])
        tris.append([idx[0], idx[2], idx[3]])

    def text(self, mtl_name, object_name, comment):
        lines = [HEADER, "# " + comment, "mtllib " + mtl_name, "o " + object_name]
        lines += ["v %.6f %.6f %.6f" % (p[0] / 16.0, p[1] / 16.0, p[2] / 16.0) for p in self.v]
        lines += ["vt %.6f %.6f" % t for t in self.vt]
        lines += ["vn %.6f %.6f %.6f" % n for n in self.vn]
        # The face goes last: Forge takes an OBJ model's particle sprite from the material of the
        # last face it bakes, and breaking a sign should throw bits of its face, as the JSON
        # plates' particle texture does.
        for material in sorted(self.groups, key=lambda m: m == "face"):
            lines.append("usemtl " + material)
            for tri in self.groups[material]:
                lines.append("f " + " ".join("%d/%d/%d" % corner for corner in tri))
        return "\n".join(lines) + "\n"


def box(mesh, lo, hi, faces, material, uv_rect):
    """Axis-aligned box faces. ``uv_rect`` (u0, v0, u1, v1) in OBJ space (v up, flip-v on)."""
    x0, y0, z0 = lo
    x1, y1, z1 = hi
    u0, v0, u1, v1 = uv_rect
    # Each face: corners counter-clockwise from outside, starting bottom-left as seen from outside.
    spec = {
        "north": ([(x1, y0, z0), (x0, y0, z0), (x0, y1, z0), (x1, y1, z0)], (0, 0, -1)),
        "south": ([(x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)], (0, 0, 1)),
        "west": ([(x0, y0, z0), (x0, y0, z1), (x0, y1, z1), (x0, y1, z0)], (-1, 0, 0)),
        "east": ([(x1, y0, z1), (x1, y0, z0), (x1, y1, z0), (x1, y1, z1)], (1, 0, 0)),
        "up": ([(x0, y1, z1), (x1, y1, z1), (x1, y1, z0), (x0, y1, z0)], (0, 1, 0)),
        "down": ([(x0, y0, z0), (x1, y0, z0), (x1, y0, z1), (x0, y0, z1)], (0, -1, 0)),
    }
    uvs = [(u0, v0), (u1, v0), (u1, v1), (u0, v1)]
    for face in faces:
        corners, normal = spec[face]
        mesh.quad(material, corners, uvs, normal)


def art_rect(width, height, size):
    """Where the art sits in its square texture, in pixels: (left, top, art width, art height).

    The art keeps the PLATE's aspect -- a whole number of pixels per block on both axes, as large
    as fits inside ART_PADDING on every side -- and is centred. It is deliberately not squished to
    fill the square. A squished texture stretched back out by the plate has a different texel
    density along each axis (5 to 1 on a 5 x 1 banner), and OpenGL picks the mip level from the
    DENSER axis, so the sparse axis is drawn from a level with a fifth of the detail it needs and
    the legend turns to mush a few blocks away. Equal density on both axes is what keeps it sharp.
    """
    per_block = (size - 2 * ART_PADDING) // max(width, height)
    art_w, art_h = per_block * width, per_block * height
    return (size - art_w) // 2, (size - art_h) // 2, art_w, art_h


def face_uv(width, height, size):
    """The art's rectangle as an OBJ uv rect (u0, v_bottom, u1, v_top), flip-v on, each edge
    brought in half a texel so the plate's rim samples the art's own edge pixels."""
    left, top, art_w, art_h = art_rect(width, height, size)
    u0 = (left + 0.5) / size
    u1 = (left + art_w - 0.5) / size
    v_top = 1.0 - (top + 0.5) / size
    v_bottom = 1.0 - (top + art_h - 0.5) / size
    return (u0, v_bottom, u1, v_top)


def sign_mesh(width, height, size, shift):
    """One plate, centred on the block across and up and down, with its post if it has one."""
    mesh = Mesh()
    half_w, half_h = width * 8.0, height * 8.0
    front = SHIFTS[shift]["front"]
    back = front + PLATE_THICKNESS
    lo = (8.0 - half_w, 8.0 - half_h, front)
    hi = (8.0 + half_w, 8.0 + half_h, back)
    # Front: the art's rectangle of its texture. The north face's first corner is (x_max, y_min),
    # which is the art's bottom-LEFT seen from in front -- so u runs from the art's left edge at
    # x_max to its right edge at x_min.
    box(mesh, lo, hi, ["north"], "face", face_uv(width, height, size))
    # Back and the four edges wear the plain metal back, as every other plate's back does.
    box(mesh, lo, hi, ["south"], "back", (0.0, 0.0, 1.0, 1.0))
    edge = 0.5 / 16.0
    box(mesh, lo, hi, ["up", "down"], "back", (0.0, 0.0, 1.0, edge))
    box(mesh, lo, hi, ["east", "west"], "back", (0.0, 0.0, edge, 1.0))
    if SHIFTS[shift]["post"]:
        # No front face: it is flush against the plate's back and could never be seen.
        box(mesh, (POST_X[0], 0.0, back), (POST_X[1], 16.0, back + POST_DEPTH),
            ["south", "east", "west", "up", "down"], "back", (0.0, 0.0, 0.25, 1.0))
    return mesh


def model_name(name, shift):
    return name if shift == "none" else "%s_%s" % (name, shift)


def mtl_text(name):
    return "\n".join([
        HEADER,
        "newmtl back",
        "map_Kd " + BACK_TEXTURE,
        "newmtl face",
        "map_Kd csm:blocks/trafficsigns/" + name,
    ]) + "\n"


# --- blockstate ----------------------------------------------------------------------------------
def inventory_transform(width, height):
    """Fit the plate to the slot face-on. Every plate is centred on the block, and Forge scales
    and rotates a blockstate transform about the block centre, so no translation is needed."""
    fit = round(0.9 / max(width, height), 3)
    front = [0, 180, 0]
    return {
        "gui": {"rotation": front, "scale": fit},
        "ground": {"translation": [0, 0.1875, 0], "scale": round(fit * 0.5, 3)},
        "fixed": {"scale": fit},
        "thirdperson_righthand": {"rotation": [75, 225, 0], "translation": [0, 0.15625, 0],
                                  "scale": round(fit * 0.6, 3)},
        "thirdperson_lefthand": {"rotation": [75, 225, 0], "translation": [0, 0.15625, 0],
                                 "scale": round(fit * 0.6, 3)},
        "firstperson_righthand": {"rotation": [0, 225, 0], "scale": round(fit * 0.6, 3)},
        "firstperson_lefthand": {"rotation": [0, 45, 0], "scale": round(fit * 0.6, 3)},
    }


def blockstate(name, width, height):
    custom = {"flip-v": True}
    facing = {}
    for key, degrees in FACINGS:
        facing[key] = {} if degrees == 0 else {
            "transform": {"rotation": [{"x": 0}, {"y": degrees}, {"z": 0}]}}
    return {
        "forge_marker": 1,
        "defaults": {"model": MODEL_PREFIX + name + ".obj", "custom": custom},
        "variants": {
            "facing": facing,
            "inventory": [{"transform": inventory_transform(width, height)}],
            "downward": {
                "false": {},
                "true": {"submodel": {"extension": {
                    "model": "csm:trafficsigns/sign_pole",
                    "transform": {"translation": [0.0, -1.0, 0.0]}}}},
            },
            "shift": {
                "none": {},
                "setback": {"model": MODEL_PREFIX + model_name(name, "setback") + ".obj",
                            "custom": custom},
                "backtoback": {"model": MODEL_PREFIX + model_name(name, "back_to_back") + ".obj",
                               "custom": custom},
            },
            "normal": [{}],
        },
    }


# --- output --------------------------------------------------------------------------------------
def outputs():
    """Every generated file as {absolute path: text}."""
    files = {}
    for name, _art, width, height, size in CATALOGUE:
        mtl = name + ".mtl"
        files[os.path.join(MODEL_DIR, mtl)] = mtl_text(name)
        for shift in SHIFTS:
            obj = model_name(name, shift)
            comment = "%d x %d block plate centred on its block, shift=%s" % (width, height, shift)
            files[os.path.join(MODEL_DIR, obj + ".obj")] = \
                sign_mesh(width, height, size, shift).text(mtl, obj, comment)
        files[os.path.join(BLOCKSTATE_DIR, name + ".json")] = \
            json.dumps(blockstate(name, width, height), indent=2) + "\n"
    return files


def build_textures(art_dir):
    from PIL import Image

    import numpy as np

    for name, art, width, height, size in CATALOGUE:
        image = Image.open(os.path.join(art_dir, art)).convert("RGBA")
        bounds = image.getchannel("A").getbbox()
        if bounds:
            image = image.crop(bounds)
        left, top, art_w, art_h = art_rect(width, height, size)
        # Resampled once, straight to the plate's aspect (an art file not at the plate's aspect,
        # like the 2.06:1 DANGER art on its 3 x 2 plate, is fitted here and not by the UVs).
        pixels = np.asarray(image.resize((art_w, art_h), Image.LANCZOS))
        # The rest of the square repeats the art's edge pixels outward (clamp to edge), alpha and
        # all. Transparent padding would bleed into the plate's rim as the mip levels average it
        # in, and so would the neighbouring atlas sprites; an edge that is transparent in the art
        # itself (rounded corners) stays transparent, since its alpha is repeated too.
        rows = np.clip(np.arange(size) - top, 0, art_h - 1)
        cols = np.clip(np.arange(size) - left, 0, art_w - 1)
        padded = Image.fromarray(np.ascontiguousarray(pixels[rows][:, cols]), "RGBA")
        path = os.path.join(TEXTURE_DIR, name + ".png")
        padded.save(path, optimize=True)
        print("wrote", os.path.relpath(path, layout.REPO_ROOT))


def normalised(text):
    return text.replace("\r\n", "\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="write nothing; exit 1 if a model or blockstate has drifted")
    parser.add_argument("--art", help="folder holding the source art; rebuilds the face textures")
    args = parser.parse_args()

    files = outputs()
    if args.check:
        drift = []
        for path, text in files.items():
            if not os.path.exists(path):
                drift.append(path)
                continue
            with open(path, encoding="utf-8", newline="") as fh:
                if normalised(fh.read()) != text:
                    drift.append(path)
        for path in drift:
            print("DRIFT", os.path.relpath(path, layout.REPO_ROOT))
        print("%d of %d files up to date" % (len(files) - len(drift), len(files)))
        return 1 if drift else 0

    for directory in (MODEL_DIR, BLOCKSTATE_DIR, TEXTURE_DIR):
        os.makedirs(directory, exist_ok=True)
    for path, text in files.items():
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        print("wrote", os.path.relpath(path, layout.REPO_ROOT))
    if args.art:
        build_textures(args.art)
    return 0


if __name__ == "__main__":
    sys.exit(main())
