#!/usr/bin/env python3
"""
Procedural generator for the Miovision SmartView 360 camera block models.

Emits two Wavefront OBJ models (+ matching MTL) used by the CSM mod's traffic-signal
detection-camera blocks:

  * miovision_360.obj      -- short variant: a back mount bracket that seats against an adjacent
                              vertical pole, a short curved "shepherd's-hook" gooseneck arm, and a
                              bell dome hanging with its lens facing down. Fits ~ within one block.
  * miovision_360_tall.obj -- tall variant: a clamp/saddle at the BOTTOM (sits on a horizontal mast
                              arm), a long straight shaft rising UP off the arm, then the hook curls
                              over the top and the bell dome hangs down from it. Matches real
                              mast-arm installs where the camera arm extends upward off the arm.

Coordinate convention (matches the mod's Blockbench-exported furniture OBJs, e.g. apple_crate):
  * 1 unit == 1 block.
  * X and Z are CENTERED on the block (-0.5 .. 0.5) so the vertical centre axis is X=0, Z=0. This
    makes the Forge blockstate `transform.rotation` y:45 steps pivot about the block centre for true
    8-way (HZEight) rotation.
  * Y runs from 0 at the block's bottom face upward (may exceed 1 for the tall riser / dome).
  * Faces are triangles `f v/vt/vn`. Winding is forced so every face normal points OUTWARD from the
    local surface centre (Forge culls back-faces -- inverted winding makes the model see-through).

Materials: `housing` (cream body + arm) and `lens` (dark glass).
Run:  python dev-env-utils/scripts/gen_miovision_obj.py
"""

import math
import os

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT_DIR = os.path.join(
    REPO_ROOT, "src", "main", "resources", "assets", "csm",
    "models", "block", "trafficsignals", "shared_models",
)

HOUSING_TEX = "csm:blocks/trafficsignals/shared_textures/miovision_housing"
LENS_TEX = "csm:blocks/trafficsignals/shared_textures/miovision_lens"

RING = 12


class Mesh:
    def __init__(self):
        self.v, self.vt, self.vn, self.faces = [], [], [], []

    def _v(self, p): self.v.append(p); return len(self.v)
    def _t(self, uv):
        self.vt.append((min(0.96, max(0.04, uv[0])), min(0.96, max(0.04, uv[1]))))
        return len(self.vt)
    def _n(self, n): self.vn.append(n); return len(self.vn)

    def rotate_y(self, deg, px=0.0, pz=0.0):
        """Rotate all geometry about the vertical axis through (px, pz) in build space. Positive deg
        is clockwise viewed from above (matching the compass/facing sense, i.e. north->east). Used to
        bake the mount-anchored diagonal variants: pivoting about the back mount point (rather than
        the block centre) keeps the bracket/pole flush against its pole while the camera swings 45deg.
        Rotates the stored normals too so winding/lighting stay correct after the move."""
        a = math.radians(deg)
        ca, sa = math.cos(a), math.sin(a)
        self.v = [(px + (x - px) * ca - (z - pz) * sa, y, pz + (x - px) * sa + (z - pz) * ca)
                  for (x, y, z) in self.v]
        self.vn = [(nx * ca - nz * sa, ny, nx * sa + nz * ca) for (nx, ny, nz) in self.vn]

    def tri(self, mat, p1, p2, p3, uv1, uv2, uv3):
        ni = self._n(_nrm(p1, p2, p3))
        self.faces.append((mat, [(self._v(p1), self._t(uv1), ni),
                                 (self._v(p2), self._t(uv2), ni),
                                 (self._v(p3), self._t(uv3), ni)]))

    def quad(self, mat, p1, p2, p3, p4, uv1, uv2, uv3, uv4):
        self.tri(mat, p1, p2, p3, uv1, uv2, uv3)
        self.tri(mat, p1, p3, p4, uv1, uv3, uv4)

    def quad_out(self, mat, verts, uvs, center):
        """Emit a quad, choosing the winding whose normal points away from `center`."""
        p1, p2, p3, p4 = verts
        n = _nrm(p1, p2, p3)
        cen = tuple(sum(p[k] for p in verts) / 4.0 for k in range(3))
        d = sum(n[k] * (cen[k] - center[k]) for k in range(3))
        if d >= 0:
            self.quad(mat, p1, p2, p3, p4, *uvs)
        else:
            self.quad(mat, p1, p4, p3, p2, uvs[0], uvs[3], uvs[2], uvs[1])

    def write(self, obj_path, mtl_name, offset=(0.5, 0.0, 0.5)):
        # Geometry is built in CENTER-origin space (X,Z about 0) because that keeps the math tidy,
        # but Minecraft/Forge align and place blocks in CORNER-origin 0..1 space. Offsetting by
        # (+0.5, 0, +0.5) on write moves the model into 0..1 so it lines up with the block edge /
        # bounding box / mast arm. Rotation still pivots about the block centre (0.5,0.5,0.5), which
        # is now the model's horizontal centre, so 8-way rotation stays in place. Normals are
        # unaffected by translation.
        ox, oy, oz = offset
        with open(obj_path, "w", newline="\n") as f:
            f.write("# Procedurally generated by dev-env-utils/scripts/gen_miovision_obj.py\n")
            f.write("# Miovision SmartView 360 camera\n")
            f.write("mtllib %s\no miovision360\n" % mtl_name)
            for x, y, z in self.v: f.write("v %.6f %.6f %.6f\n" % (x + ox, y + oy, z + oz))
            for u, w in self.vt: f.write("vt %.6f %.6f\n" % (u, w))
            for x, y, z in self.vn: f.write("vn %.6f %.6f %.6f\n" % (x, y, z))
            cur = None
            for mat, idx in self.faces:
                if mat != cur: f.write("usemtl %s\n" % mat); cur = mat
                f.write("f %s\n" % " ".join("%d/%d/%d" % t for t in idx))


def _nrm(p1, p2, p3):
    ax, ay, az = p2[0]-p1[0], p2[1]-p1[1], p2[2]-p1[2]
    bx, by, bz = p3[0]-p1[0], p3[1]-p1[1], p3[2]-p1[2]
    nx, ny, nz = ay*bz-az*by, az*bx-ax*bz, ax*by-ay*bx
    m = math.sqrt(nx*nx+ny*ny+nz*nz) or 1.0
    return (nx/m, ny/m, nz/m)


# ---- centerline primitives (built in the X=0 / Z-Y plane) ----------------------------------
def straight(p0, p1, n):
    return [tuple(p0[k] + (p1[k]-p0[k])*(i/n) for k in range(3)) for i in range(n+1)]


def arc_zy(center, radius, a0_deg, a1_deg, n, z_sign=1.0, y_sign=1.0):
    pts = []
    for i in range(n+1):
        a = math.radians(a0_deg + (a1_deg-a0_deg)*(i/n))
        pts.append((center[0],
                    center[1] + y_sign*radius*math.sin(a),
                    center[2] + z_sign*radius*math.cos(a)))
    return pts


def join(*chains):
    out = []
    for c in chains:
        if out and _close(out[-1], c[0]):
            out.extend(c[1:])
        else:
            out.extend(c)
    return out


def _close(a, b, eps=1e-6):
    return all(abs(a[k]-b[k]) < eps for k in range(3))


# ---- surface builders (winding forced outward) ---------------------------------------------
def _cap_ring(mesh, ringpts, center_pt, inside_pt, mat):
    """Close a tube end with a triangle fan, normal pointing away from `inside_pt` (outward)."""
    n = len(ringpts)
    for j in range(n):
        a, b = ringpts[j], ringpts[(j + 1) % n]
        nrm = _nrm(center_pt, a, b)
        d = sum(nrm[k] * (center_pt[k] - inside_pt[k]) for k in range(3))
        if d >= 0:
            mesh.tri(mat, center_pt, a, b, (0.5, 0.5), (0.9, 0.5), (0.5, 0.9))
        else:
            mesh.tri(mat, center_pt, b, a, (0.5, 0.5), (0.5, 0.9), (0.9, 0.5))


def sweep_tube(mesh, centerline, radius, mat, ring=RING, cap_ends=True, up_seed=(1.0, 0.0, 0.0)):
    # up_seed is the reference axis for the cross-section frame; it must NOT be (near) parallel to the
    # tangent anywhere along the path or the frame degenerates and the tube visibly twists. Default
    # (1,0,0) suits paths in the Z-Y plane; pass (0,0,1) for a loop in the X-Y plane, etc.
    n = len(centerline)
    tangents = []
    for i in range(n):
        a = centerline[max(0, i-1)]
        b = centerline[min(n-1, i+1)]
        t = (b[0]-a[0], b[1]-a[1], b[2]-a[2])
        m = math.sqrt(sum(c*c for c in t)) or 1.0
        tangents.append((t[0]/m, t[1]/m, t[2]/m))
    rings = []
    up = up_seed
    for i in range(n):
        t = tangents[i]
        ux, uy, uz = (up[1]*t[2]-up[2]*t[1], up[2]*t[0]-up[0]*t[2], up[0]*t[1]-up[1]*t[0])
        mu = math.sqrt(ux*ux+uy*uy+uz*uz)
        if mu < 1e-6: ux, uy, uz, mu = 0.0, 0.0, 1.0, 1.0
        ux, uy, uz = ux/mu, uy/mu, uz/mu
        wx, wy, wz = (t[1]*uz-t[2]*uy, t[2]*ux-t[0]*uz, t[0]*uy-t[1]*ux)
        c = centerline[i]
        rings.append([(c[0]+radius*(math.cos(2*math.pi*j/ring)*ux+math.sin(2*math.pi*j/ring)*wx),
                       c[1]+radius*(math.cos(2*math.pi*j/ring)*uy+math.sin(2*math.pi*j/ring)*wy),
                       c[2]+radius*(math.cos(2*math.pi*j/ring)*uz+math.sin(2*math.pi*j/ring)*wz))
                      for j in range(ring)])
    for i in range(n-1):
        seg_center = tuple((centerline[i][k]+centerline[i+1][k])/2 for k in range(3))
        for j in range(ring):
            j2 = (j+1) % ring
            verts = [rings[i][j], rings[i][j2], rings[i+1][j2], rings[i+1][j]]
            u0, u1 = j/ring, (j+1)/ring
            v0, v1 = i/(n-1), (i+1)/(n-1)
            mesh.quad_out(mat, verts, [(u0, v0), (u1, v0), (u1, v1), (u0, v1)], seg_center)
    if cap_ends and n >= 2:
        _cap_ring(mesh, rings[0], centerline[0], centerline[1], mat)
        _cap_ring(mesh, rings[-1], centerline[-1], centerline[-2], mat)


def revolve(mesh, profile, axis_xz, mat, ring=RING):
    ax, az = axis_xz
    rings = [[(ax+r*math.cos(2*math.pi*j/ring), y, az+r*math.sin(2*math.pi*j/ring))
              for j in range(ring)] for (y, r) in profile]
    for i in range(len(profile)-1):
        ymid = (profile[i][0]+profile[i+1][0])/2
        center = (ax, ymid, az)
        for j in range(ring):
            j2 = (j+1) % ring
            verts = [rings[i][j], rings[i][j2], rings[i+1][j2], rings[i+1][j]]
            u0, u1 = j/ring, (j+1)/ring
            v0, v1 = i/(len(profile)-1), (i+1)/(len(profile)-1)
            mesh.quad_out(mat, verts, [(u0, v0), (u1, v0), (u1, v1), (u0, v1)], center)


def disc_down(mesh, axis_xz, r_outer, r_inner, y, mat, ring=RING):
    """Flat annulus facing straight down (normal -Y)."""
    cx, cz = axis_xz
    for j in range(ring):
        a0, a1 = 2*math.pi*j/ring, 2*math.pi*(j+1)/ring
        po0 = (cx+r_outer*math.cos(a0), y, cz+r_outer*math.sin(a0))
        po1 = (cx+r_outer*math.cos(a1), y, cz+r_outer*math.sin(a1))
        pi0 = (cx+r_inner*math.cos(a0), y, cz+r_inner*math.sin(a0))
        pi1 = (cx+r_inner*math.cos(a1), y, cz+r_inner*math.sin(a1))
        # wind so normal = -Y
        mesh.quad_out(mat, [po0, pi0, pi1, po1],
                      [(0, 0), (0.4, 0), (0.4, 1), (0, 1)], (cx, y+1.0, cz))


def lens_disc(mesh, axis_xz, radius, y, mat, ring=RING):
    """Solid lens disc on the dome underside, wound so the normal points down (visible from below)."""
    cx, cz = axis_xz
    c = (cx, y, cz)
    for j in range(ring):
        a0, a1 = 2*math.pi*j/ring, 2*math.pi*(j+1)/ring
        pa = (cx+radius*math.cos(a0), y, cz+radius*math.sin(a0))
        pb = (cx+radius*math.cos(a1), y, cz+radius*math.sin(a1))
        ua = (0.5+0.45*math.cos(a0), 0.5+0.45*math.sin(a0))
        ub = (0.5+0.45*math.cos(a1), 0.5+0.45*math.sin(a1))
        if _nrm(c, pa, pb)[1] > 0:   # normal points up -> flip so it faces down
            pa, pb, ua, ub = pb, pa, ub, ua
        mesh.tri(mat, c, pa, pb, (0.5, 0.5), ua, ub)


def box(mesh, x0, x1, y0, y1, z0, z1, mat):
    c = [(x0, y0, z0), (x1, y0, z0), (x1, y0, z1), (x0, y0, z1),
         (x0, y1, z0), (x1, y1, z0), (x1, y1, z1), (x0, y1, z1)]
    uv = [(0, 0), (1, 0), (1, 1), (0, 1)]
    cen = ((x0+x1)/2, (y0+y1)/2, (z0+z1)/2)
    for a, b, cc, d in [(3, 2, 1, 0), (4, 5, 6, 7), (0, 1, 5, 4),
                        (2, 3, 7, 6), (1, 2, 6, 5), (3, 0, 4, 7)]:
        mesh.quad_out(mat, [c[a], c[b], c[cc], c[d]], uv, cen)


# ---- bell dome -----------------------------------------------------------------------------
# Neck radius (0.065) is a touch wider than the arm tube (0.055) so the dome wraps over the arm
# where they join -- no see-through ring at the camera/arm junction.
DOME_PROFILE = [
    (0.00, 0.065), (-0.03, 0.11), (-0.07, 0.165), (-0.12, 0.205),
    (-0.18, 0.230), (-0.24, 0.240), (-0.28, 0.235),
]
DOME_HEIGHT = 0.28
DOME_RIM_R = 0.235
LENS_R = 0.135
ARM_R = 0.055
WIRE_R = 0.022


def add_wire_loop(mesh, pole_bottom, bracket_pt):
    """A small black drip-loop of cable: out the bottom of the camera pole, around a full hanging
    circle, and back into the side-mount bracket. `pole_bottom` and `bracket_pt` are (x, y, z) in the
    build (centred) space; the loop is a complete circle in the X=0 (Z-Y) plane below them, with two
    short tails connecting it to the pole bottom and the bracket."""
    cz = (pole_bottom[2] + bracket_pt[2]) / 2 + 0.02
    cy = min(pole_bottom[1], bracket_pt[1]) - 0.16
    r = 0.11

    def on_circle(deg):
        a = math.radians(deg)
        return (0.0, cy + r * math.sin(a), cz + r * math.cos(a))

    # full closed circle (last point repeats the first to seal the loop)
    n = 24
    circle = [on_circle(360.0 * i / n) for i in range(n + 1)]
    sweep_tube(mesh, circle, WIRE_R, "wire", ring=6, cap_ends=False)
    # short tails: pole bottom -> upper-left of the circle, bracket -> upper-right of the circle
    sweep_tube(mesh, [pole_bottom, on_circle(150.0)], WIRE_R, "wire", ring=6)
    sweep_tube(mesh, [bracket_pt, on_circle(30.0)], WIRE_R, "wire", ring=6)


def add_dome(mesh, axis_xz, neck_y):
    profile = [(neck_y+dy, r) for (dy, r) in DOME_PROFILE]
    revolve(mesh, profile, axis_xz, "housing")
    rim_y = neck_y - DOME_HEIGHT
    disc_down(mesh, axis_xz, DOME_RIM_R, LENS_R, rim_y, "housing")
    # Lens sits flush in the rim opening, a hair lower and slightly oversized so it overlaps under
    # the housing's inner edge -- closes the thin see-through ring that a recessed lens left.
    lens_disc(mesh, axis_xz, LENS_R + 0.012, rim_y - 0.002, "lens")


# ---- assemblies ----------------------------------------------------------------------------
def build_short():
    m = Mesh()
    # Side-mount on a short camera pole: a bracket flush to the back edge (z=0.50), with the camera
    # pole running a little below the mount and curving over the top to the dome.
    shaft_z = 0.34
    shaft_top = 1.00
    shaft_bottom = 0.05     # camera pole extends below the mount
    hook_r = 0.33           # hook radius = how far the camera reaches out (deeper = farther)
    by0, by1 = 0.30, 0.82   # side-mount bracket region
    box(m, -0.11, 0.11, by0, by1, shaft_z - 0.04, 0.50, "housing")
    box(m, -0.07, 0.07, by0 + 0.08, by1 - 0.08, 0.44, 0.50, "housing")  # boss toward the pole
    shaft = straight((0.0, shaft_bottom, shaft_z), (0.0, shaft_top, shaft_z), 8)
    hook = arc_zy(center=(0.0, shaft_top, shaft_z - hook_r), radius=hook_r, a0_deg=0.0, a1_deg=180.0,
                  n=14)
    # dip the arm's end ~0.1 into the dome so its (capped) end is hidden inside the housing
    dome_axis_z = shaft_z - 2 * hook_r
    dip = straight((0.0, shaft_top, dome_axis_z), (0.0, shaft_top - 0.10, dome_axis_z), 2)
    sweep_tube(m, join(shaft, hook, dip), ARM_R, "housing")
    add_dome(m, axis_xz=(0.0, dome_axis_z), neck_y=shaft_top)
    add_wire_loop(m, (0.0, shaft_bottom, shaft_z), (0.0, by0 + 0.06, 0.47))
    return m


def build_tall():
    m = Mesh()
    # Side-mount on a long camera pole (same mounting idea as the short variant, just attaching
    # higher up). A bracket flush to the back edge clamps to the pole; the camera pole rises to the
    # hook + dome and runs a touch below the bracket.
    shaft_z = 0.34          # toward the back, matching the short variant
    shaft_top = 4.25        # ~+50% taller pole so the camera sits higher (was 2.90)
    shaft_bottom = -0.15    # camera pole extends a bit further below the mount
    hook_r = 0.30           # deeper curve so the camera reaches well out (matches the short)
    by0, by1 = 0.20, 0.90   # side-mount bracket region
    box(m, -0.11, 0.11, by0, by1, shaft_z - 0.04, 0.50, "housing")
    box(m, -0.07, 0.07, by0 + 0.10, by1 - 0.10, 0.44, 0.50, "housing")  # boss toward the pole
    shaft = straight((0.0, shaft_bottom, shaft_z), (0.0, shaft_top, shaft_z), 30)
    hook = arc_zy(center=(0.0, shaft_top, shaft_z - hook_r), radius=hook_r,
                  a0_deg=0.0, a1_deg=180.0, n=14)
    dome_axis_z = shaft_z - 2 * hook_r
    dip = straight((0.0, shaft_top, dome_axis_z), (0.0, shaft_top - 0.10, dome_axis_z), 2)
    sweep_tube(m, join(shaft, hook, dip), ARM_R, "housing")
    add_dome(m, axis_xz=(0.0, dome_axis_z), neck_y=shaft_top)
    add_wire_loop(m, (0.0, shaft_bottom, shaft_z), (0.0, by0 + 0.06, 0.47))
    return m


def write_mtl(path):
    with open(path, "w", newline="\n") as f:
        f.write("# Procedurally generated by gen_miovision_obj.py\n")
        f.write("newmtl housing\nmap_Kd %s\n\n" % HOUSING_TEX)
        f.write("newmtl lens\nmap_Kd %s\n\n" % LENS_TEX)
        f.write("newmtl wire\nmap_Kd csm:blocks/trafficsignals/shared_textures/metal_black\n\n")
        f.write("newmtl none\n")


def _center(mesh):
    xs = [p[0] for p in mesh.v]; ys = [p[1] for p in mesh.v]; zs = [p[2] for p in mesh.v]
    return ((min(xs)+max(xs))/2, (min(ys)+max(ys))/2, (min(zs)+max(zs))/2)


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    mtl_name = "miovision_360.mtl"
    write_mtl(os.path.join(OUT_DIR, mtl_name))
    short = build_short(); short.write(os.path.join(OUT_DIR, "miovision_360.obj"), mtl_name)
    tall = build_tall(); tall.write(os.path.join(OUT_DIR, "miovision_360_tall.obj"), mtl_name)

    # Mount-anchored diagonal variants. The block stores an 8-way DirectionEight facing; the four
    # diagonals would otherwise rotate the whole model about the block centre, swinging the back
    # bracket off into an empty corner. Instead the diagonals point at these pre-swung models: the
    # base mesh pivoted +/-45deg about the BACK MOUNT POINT (build z=0.50, the +Z bracket face), so
    # the bracket stays flush against its pole and only the camera/arm swings. The blockstate then
    # places diagr/diagl at a 90deg-step cardinal rotation (see the *.json), landing the bracket on
    # a real block face for every diagonal. PIVOT_Z must match the bracket's back face.
    PIVOT_Z = 0.50
    for build, base in ((build_short, "miovision_360"), (build_tall, "miovision_360_tall")):
        for sfx, deg in (("diagr", 45.0), ("diagl", -45.0)):
            dm = build()
            dm.rotate_y(deg, 0.0, PIVOT_Z)
            dm.write(os.path.join(OUT_DIR, "%s_%s.obj" % (base, sfx)), mtl_name)

    # Inventory-only copies, centred on the ORIGIN (0,0,0). Item-frame/GUI rotation pivots about the
    # model origin (unlike world placement, which pivots about the block centre), so an origin-
    # centred model stays in view -- the same trick the furniture OBJs (anchor.obj) use. The world
    # variants keep the 0..1 models; only the blockstate "inventory" variant points at these.
    for mesh, fname in ((build_short(), "miovision_360_inv.obj"),
                        (build_tall(), "miovision_360_tall_inv.obj")):
        cx, cy, cz = _center(mesh)
        mesh.write(os.path.join(OUT_DIR, fname), mtl_name, offset=(-cx, -cy, -cz))

    for name, mesh in (("miovision_360", short), ("miovision_360_tall", tall)):
        xs = [p[0] for p in mesh.v]; ys = [p[1] for p in mesh.v]; zs = [p[2] for p in mesh.v]
        # outward-normal self-check relative to each face's own normal vs model bbox centre
        cen = (sum(xs)/len(xs), sum(ys)/len(ys), sum(zs)/len(zs))
        out = 0
        for _, idx in mesh.faces:
            vs = [mesh.v[i-1] for i, _, _ in idx]
            n = _nrm(*vs[:3])
            fc = tuple(sum(p[k] for p in vs)/3 for k in range(3))
            if sum(n[k]*(fc[k]-cen[k]) for k in range(3)) >= 0:
                out += 1
        print("%-22s verts=%4d tris=%4d  y[%.2f,%.2f]  outward~%d%%" % (
            name, len(mesh.v), len(mesh.faces), min(ys), max(ys),
            round(100*out/len(mesh.faces))))


if __name__ == "__main__":
    main()
