package com.micatechnologies.minecraft.csm.trafficsigns;

// GENERATED by dev-env-utils/scripts/gen_road_markers.py -- do not edit by hand; change the
// catalogue there and re-run it (its --check fails when this file and the textures disagree).

/**
 * The eight mile marker plates (MUTCD D10-1 to D10-5) and where each draws what its tile entity
 * holds, in model units of the unturned model (the plate faces north, the reader stands north of
 * it, and the reader's x runs the other way from the model's: {@code modelX = 16 - readerX}).
 * Every legend is centred on the plate's centre line. {@code lift} is how far the blockstate's
 * facing transform lifts the whole model so the plate's bottom edge is on the block's floor; the
 * legend is lifted with it.
 *
 * <p>{@code mile} is, for a stacked plate, one {@code (centreY, cap)} pair per digit from the
 * top; for an enhanced plate one {@code (centreY, cap, maxWidth)} run. {@code tenth} and
 * {@code direction} are {@code (centreY, cap, maxWidth)} runs, {@code shield} a
 * {@code (centreY, size)} square. The glyph tables give each glyph's cell on the sheet
 * ({@code u0, v0, u1, v1} in sprite units) and its metrics in sheet pixels
 * ({@code cellW, cellH, originX, baseline, cap, advance}), the convention
 * {@code GuideSignFontRenderer} draws in.</p>
 *
 * @since 2026.9
 */
public enum MileMarkerLayout {

  D10_1("mile_marker_sign_1", "D10-1", 1, true, false, 0.0000f,
      new float[] {8.0000f, 4.0000f},
      null,
      null,
      null),
  D10_2("mile_marker_sign_2", "D10-2", 2, true, false, 1.0000f,
      new float[] {9.0000f, 4.0000f, 3.0000f, 4.0000f},
      null,
      null,
      null),
  D10_3("mile_marker_sign_3", "D10-3", 3, true, false, 4.0000f,
      new float[] {12.0000f, 4.0000f, 6.0000f, 4.0000f, 0.0000f, 4.0000f},
      null,
      null,
      null),
  D10_1A("mile_marker_sign_1_intermediate", "D10-1a", 1, true, true, 1.0000f,
      new float[] {9.0000f, 4.0000f},
      new float[] {3.0000f, 4.0000f, 5.4667f},
      null,
      null),
  D10_2A("mile_marker_sign_2_intermediate", "D10-2a", 2, true, true, 4.0000f,
      new float[] {12.0000f, 4.0000f, 6.0000f, 4.0000f},
      new float[] {0.0000f, 4.0000f, 5.4667f},
      null,
      null),
  D10_3A("mile_marker_sign_3_intermediate", "D10-3a", 3, true, true, 8.0000f,
      new float[] {16.0000f, 4.0000f, 10.0000f, 4.0000f, 4.0000f, 4.0000f},
      new float[] {-4.0000f, 4.0000f, 5.4667f},
      null,
      null),
  D10_4("mile_marker_sign_enhanced", "D10-4", 3, false, false, 10.0000f,
      new float[] {-4.0000f, 5.3333f, 10.6667f},
      null,
      new float[] {21.3333f, 4.0000f, 10.6667f},
      new float[] {12.3333f, 8.6667f}),
  D10_5("mile_marker_sign_enhanced_intermediate", "D10-5", 3, false, true, 12.0000f,
      new float[] {0.5000f, 5.3333f, 10.6667f},
      new float[] {-7.8333f, 5.3333f, 10.6667f},
      new float[] {24.5000f, 4.0000f, 10.6667f},
      new float[] {15.5000f, 8.6667f});

  /** The glyph sheet's sprite. */
  public static final String SHEET = "csm:blocks/trafficsigns/mile_marker_glyphs";

  /** The characters of {@link #SERIES_D}, in order. */
  public static final String SERIES_D_CHARS = "0123456789.";

  /** The mile number's FHWA Series D numerals and point. */
  public static final float[][] SERIES_D = {
      {0.0000f, 0.0000f, 2.0000f, 3.0000f, 32.0000f, 48.0000f, 3.2500f, 40.0000f, 28.0000f, 25.5000f},
      {2.0000f, 0.0000f, 4.0000f, 3.0000f, 32.0000f, 48.0000f, 9.3750f, 40.0000f, 28.0000f, 13.2500f},
      {4.0000f, 0.0000f, 6.0000f, 3.0000f, 32.0000f, 48.0000f, 3.7500f, 40.0000f, 28.0000f, 24.5000f},
      {6.0000f, 0.0000f, 8.0000f, 3.0000f, 32.0000f, 48.0000f, 4.0000f, 40.0000f, 28.0000f, 24.0000f},
      {8.0000f, 0.0000f, 10.0000f, 3.0000f, 32.0000f, 48.0000f, 3.6250f, 40.0000f, 28.0000f, 24.7500f},
      {10.0000f, 0.0000f, 12.0000f, 3.0000f, 32.0000f, 48.0000f, 3.7500f, 40.0000f, 28.0000f, 24.5000f},
      {12.0000f, 0.0000f, 14.0000f, 3.0000f, 32.0000f, 48.0000f, 3.7500f, 40.0000f, 28.0000f, 24.5000f},
      {14.0000f, 0.0000f, 16.0000f, 3.0000f, 32.0000f, 48.0000f, 4.5000f, 40.0000f, 28.0000f, 23.0000f},
      {0.0000f, 3.0000f, 2.0000f, 6.0000f, 32.0000f, 48.0000f, 3.7500f, 40.0000f, 28.0000f, 24.5000f},
      {2.0000f, 3.0000f, 4.0000f, 6.0000f, 32.0000f, 48.0000f, 3.7500f, 40.0000f, 28.0000f, 24.5000f},
      {4.0000f, 3.0000f, 6.0000f, 6.0000f, 32.0000f, 48.0000f, 12.3750f, 40.0000f, 28.0000f, 7.2500f}
  };

  /** The guide sign font's numerals, for a route number on a shield,
   * exactly as the route marker sign sets it. */
  public static final float[][] GUIDE = {
      {0.0000f, 6.0000f, 2.0000f, 8.2500f, 32.0000f, 36.0000f, 4.0000f, 26.0000f, 20.0000f, 20.1450f},
      {2.0000f, 6.0000f, 4.0000f, 8.2500f, 32.0000f, 36.0000f, 4.0000f, 26.0000f, 20.0000f, 10.5950f},
      {4.0000f, 6.0000f, 6.0000f, 8.2500f, 32.0000f, 36.0000f, 4.0000f, 26.0000f, 20.0000f, 18.9500f},
      {6.0000f, 6.0000f, 8.0000f, 8.2500f, 32.0000f, 36.0000f, 4.0000f, 26.0000f, 20.0000f, 18.9500f},
      {8.0000f, 6.0000f, 10.0000f, 8.2500f, 32.0000f, 36.0000f, 4.0000f, 26.0000f, 20.0000f, 21.3400f},
      {10.0000f, 6.0000f, 12.0000f, 8.2500f, 32.0000f, 36.0000f, 4.0000f, 26.0000f, 20.0000f, 18.9500f},
      {12.0000f, 6.0000f, 14.0000f, 8.2500f, 32.0000f, 36.0000f, 4.0000f, 26.0000f, 20.0000f, 18.9500f},
      {14.0000f, 6.0000f, 16.0000f, 8.2500f, 32.0000f, 36.0000f, 4.0000f, 26.0000f, 20.0000f, 18.9500f},
      {0.0000f, 9.0000f, 2.0000f, 11.2500f, 32.0000f, 36.0000f, 4.0000f, 26.0000f, 20.0000f, 18.9200f},
      {2.0000f, 9.0000f, 4.0000f, 11.2500f, 32.0000f, 36.0000f, 4.0000f, 26.0000f, 20.0000f, 18.9500f}
  };

  /** NORTH, SOUTH, EAST and WEST in Series B, in that order. */
  public static final float[][] DIRECTION = {
      {0.0000f, 12.0000f, 8.0000f, 14.0000f, 128.0000f, 32.0000f, 34.5000f, 26.0000f, 20.0000f, 59.0000f},
      {8.0000f, 12.0000f, 16.0000f, 14.0000f, 128.0000f, 32.0000f, 35.1250f, 26.0000f, 20.0000f, 57.7500f},
      {0.0000f, 14.0000f, 8.0000f, 16.0000f, 128.0000f, 32.0000f, 43.0000f, 26.0000f, 20.0000f, 42.0000f},
      {8.0000f, 14.0000f, 16.0000f, 16.0000f, 128.0000f, 32.0000f, 42.0000f, 26.0000f, 20.0000f, 44.0000f}
  };

  private final String registryName;
  private final String code;
  private final int digits;
  private final boolean stacked;
  private final boolean tenth;
  private final float lift;
  private final float[] mileSlot;
  private final float[] tenthSlot;
  private final float[] directionSlot;
  private final float[] shieldSlot;

  MileMarkerLayout(String registryName, String code, int digits, boolean stacked,
      boolean tenth, float lift, float[] mileSlot, float[] tenthSlot, float[] directionSlot,
      float[] shieldSlot) {
    this.registryName = registryName;
    this.code = code;
    this.digits = digits;
    this.stacked = stacked;
    this.tenth = tenth;
    this.lift = lift;
    this.mileSlot = mileSlot;
    this.tenthSlot = tenthSlot;
    this.directionSlot = directionSlot;
    this.shieldSlot = shieldSlot;
  }

  public String getRegistryName() {
    return registryName;
  }

  /** The MUTCD sign code, for the editor's title. */
  public String getCode() {
    return code;
  }

  /** How many digits the mile number has: exactly this many on a stacked plate, at most this
   * many on an enhanced one. */
  public int getDigits() {
    return digits;
  }

  /** Whether the digits are stacked one above the other (D10-1 to D10-3a). */
  public boolean isStacked() {
    return stacked;
  }

  /** Whether the plate has a tenth-of-a-mile panel. */
  public boolean hasTenth() {
    return tenth;
  }

  /** Whether the plate carries a direction, a route shield and a route number. */
  public boolean isEnhanced() {
    return shieldSlot != null;
  }

  /** How far the blockstate lifts the model, in model units: the plate's bottom edge is then
   * on the block's floor. */
  public float getLift() {
    return lift;
  }

  public float[] getMileSlot() {
    return mileSlot;
  }

  public float[] getTenthSlot() {
    return tenthSlot;
  }

  public float[] getDirectionSlot() {
    return directionSlot;
  }

  public float[] getShieldSlot() {
    return shieldSlot;
  }

  /** The smallest mile number the plate carries: a two-digit plate starts at 10. */
  public int getMinMile() {
    return stacked && digits > 1 ? (int) Math.pow(10, digits - 1) : 0;
  }

  /** The largest mile number the plate carries. */
  public int getMaxMile() {
    return (int) Math.pow(10, digits) - 1;
  }

  /** The number a newly placed marker shows. */
  public int getDefaultMile() {
    return Math.max(getMinMile(), Math.min(getMaxMile(), isEnhanced() ? 260 : 142));
  }
}
