name: Build Mod Pre-Release (Main Branch)

on:
  push:
    branches:
      - main
      - master

jobs:
  assemble_pre_release:
    name: Assemble Mod and Publish Pre-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Create pre-release version number
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
          newTag="pre-$calculatedSha"
          echo "PRE_TAG=$newTag" >> $GITHUB_ENV

      - name: Create pre-release tag
        run: |
          git tag "${{env.PRE_TAG}}" "${{ github.sha }}"
          git push origin "${{env.PRE_TAG}}"

      - name: Assemble mod with Gradle
        run: ./gradlew build -Dhttp.socketTimeout=60000 -Dhttp.connectionTimeout=60000 -Dorg.gradle.internal.http.socketTimeout=60000 -Dorg.gradle.internal.http.connectionTimeout=60000

      - name: Save Mod version to GITHUB_ENV
        run: echo "version_number=$(${{github.workspace}}/gradlew -q printVersionNumber)" >> $GITHUB_ENV

      - name: Save Game version to GITHUB_ENV
        run: echo "mc_version_number=$(${{github.workspace}}/gradlew -q printGameVersionNumber)" >> $GITHUB_ENV

      - name: Copy assembled mod .jar to GitHub Actions workspace
        run: cp ./build/libs/minecraft-city-super-mod-${{env.version_number}}.jar ./

      - name: Calculate Hashes for the Jar
        id: calculate-hashes
        run: |
          sha1=$(sha1sum ./minecraft-city-super-mod-${{env.version_number}}.jar | awk '{print $1}')
          md5=$(md5sum ./minecraft-city-super-mod-${{env.version_number}}.jar | awk '{print $1}')
          sha256=$(sha256sum ./minecraft-city-super-mod-${{env.version_number}}.jar | awk '{print $1}')
          crc32=$(cksum ./minecraft-city-super-mod-${{env.version_number}}.jar | awk '{print $1}')
          echo "::set-output name=sha1::$sha1"
          echo "::set-output name=md5::$md5"
          echo "::set-output name=sha256::$sha256"
          echo "::set-output name=crc32::$crc32"

      - name: Create pre-release entry
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{env.PRE_TAG}}
          name: Pre-Release ${{env.version_number}} (${{ env.mc_version_number }})
          body: |
            Automated Pre-Release of CSM
            Mod Version: ${{ env.version_number }}
            Game Version: ${{ env.mc_version_number }}

            SHA-1: `${{ steps.calculate-hashes.outputs.sha1 }}`
            SHA-256: `${{ steps.calculate-hashes.outputs.sha256 }}`
            MD5: `${{ steps.calculate-hashes.outputs.md5 }}`
            CRC-32: `${{ steps.calculate-hashes.outputs.crc32 }}`
            
            NOTICE: This is a pre-release version of the mod and is not 
            guaranteed to be stable or permanently available for download/usage.
          draft: false
          prerelease: true
          generate_release_notes: true
          files: |
            minecraft-city-super-mod-${{env.version_number}}.jar