# Script to build pre-release tags containing an assembled mod jar for each push
name: Build and Assemble Mod

on: [push]

jobs:
  build:
    name: Assemble Mod .Jar 
    runs-on: ubuntu-latest
    steps:
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Assemble mod with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assemble
      - name: Create release entry
        id: create-release-entry
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: csm-devbuild-$${{ github.sha }}
          release_name: Dev Build $${{ github.sha }}
          draft: false
          prerelease: true
      - name: Upload assembled mod .jar
        id: upload-assembled-release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release-entry.outputs.upload_url }}
          asset_path: ./build/libs/modid-1.0.jar
          asset_name: csm-devbuild-$${{ github.sha }}.jar
          asset_content_type: application/java-archive
