name: Cleanup Old/Outdated Mod Pre-Release(s)

on:
  workflow_run:
    workflows: [ "Build Mod Release/Pre-Release (Main Branch)" ]
    types:
      - completed

jobs:
  cleanup_pre_release:
    name: Cleanup Old/Outdated Mod Pre-Release(s)
    runs-on: ubuntu-latest
    steps:
      - name: Delete old pre-releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          delete_expired_data: '90'       # Delete releases older than 90 days
          delete_prerelease_only: 'true'  # Only target pre-releases
          keep_latest: '3'                # Keep the latest 3 pre-releases minimum
          keep_min_download_counts: '5'   # Keep all pre-releases with at least 5 downloads
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}